'\" t
.\"     Title: appstream-builder
.\"    Author: Richard Hughes <richard@hughsie.com>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 03/02/2019
.\"    Manual: User Commands
.\"    Source: User Commands
.\"  Language: English
.\"
.TH "APPSTREAM\-BUILDER" "1" "" "User Commands" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
appstream-builder \- Build AppStream metadata
.SH "SYNOPSIS"
.HP \w'\fBappstream\-builder\fR\ 'u
\fBappstream\-builder\fR [OPTION...]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBappstream\-builder\fR
command\&.
.PP
\fBappstream\-builder\fR
allows you to build AppStream metadata for your distro packages\&.
.SH "AUTHOR"
.PP
This manual page was written by Richard Hughes
<richard@hughsie\&.com>\&.
