'\" t
.\"     Title: appstream-util
.\"    Author: Richard Hughes <richard@hughsie.com>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 03/02/2019
.\"    Manual: User Commands
.\"    Source: User Commands
.\"  Language: English
.\"
.TH "APPSTREAM\-UTIL" "1" "" "User Commands" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
appstream-util \- Manipulate AppStream, AppData and MetaInfo metadata
.SH "SYNOPSIS"
.HP \w'\fBappstream\-util\fR\ 'u
\fBappstream\-util\fR [OPTION...]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBappstream\-util\fR
command\&.
.PP
\fBappstream\-util\fR
allows you to manipulate and validate AppStream, AppData and MetaInfo for syntax, formatting and style guidelines\&.
.SH "AUTHOR"
.PP
This manual page was written by Richard Hughes
<richard@hughsie\&.com>\&.
