'\" t
.\"     Title: cd-create-profile
.\"    Author: Richard Hughes
.\" Generator: DocBook XSL Stylesheets v1.79.2 <http://docbook.sf.net/>
.\"      Date: 8 April, 2011
.\"    Manual: User Commands
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "CD\-CREATE\-PROFILE" "1" "" "[FIXME: source]" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
cd-create-profile \- Color Manager Profile Creation Tool
.SH "SYNOPSIS"
.HP \w'\fBcd\-create\-profile\fR\ 'u
\fBcd\-create\-profile\fR [\fB\-\-verbose\fR]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBcd\-create\-profile\fR
command\&.
.PP
\fBcd\-create\-profile\fR
allows an administrator to create ICC profiles on their system\&.
.SH "OPTIONS"
.PP
This program follows the usual
GNU
command line syntax, with long options starting with two dashes (\(oq\-\(cq)\&. A summary of options is included below\&.
.PP
\fB\-\-help\fR
.RS 4
Show summary of options\&.
.RE
.PP
\fB\-\-description (optional)\fR
.RS 4
Sets the profile description\&.
.RE
.PP
\fB\-\-copyright (optional)\fR
.RS 4
Sets the profile copyright\&.
.RE
.PP
\fB\-\-model (optional)\fR
.RS 4
Sets the profile model\&.
.RE
.PP
\fB\-\-manufacturer (optional)\fR
.RS 4
Sets the profile manufacturer\&.
.RE
.PP
\fB\-\-srgb\-palette\fR
.RS 4
Specifies a comma separated values file that is used for the named color\&.
.sp
The format of the CSV file must be "Color Name",0\-255(red),0\-255(green),0\-255(blue)\&.
.RE
.PP
\fB\-\-output\fR
.RS 4
Specifies the output ICC filename\&.
.RE
.PP
\fB\-\-nc\-prefix (optional)\fR
.RS 4
Specifies the named color palette prefix\&.
.RE
.PP
\fB\-\-nc\-suffix (optional)\fR
.RS 4
Specifies the named color palette suffix\&.
.RE
.SH "AUTHOR"
.PP
This manual page was written by Richard Hughes
<richard@hughsie\&.com>\&.
