'\" t
.\"     Title: cd-fix-profile
.\"    Author: Richard Hughes
.\" Generator: DocBook XSL Stylesheets v1.79.2 <http://docbook.sf.net/>
.\"      Date: 8 April, 2011
.\"    Manual: User Commands
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "CD\-FIX\-PROFILE" "1" "" "[FIXME: source]" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
cd-fix-profile \- Color Manager Testing Tool
.SH "SYNOPSIS"
.HP \w'\fBcd\-fix\-profile\fR\ 'u
\fBcd\-fix\-profile\fR [\fB\-\-verbose\fR]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBcd\-fix\-profile\fR
command\&.
.PP
\fBcd\-fix\-profile\fR
allows an administrator to modify and fix ICC profiles on their system\&.
.PP
The program will also repair common errors found in profiles\&.
.SH "OPTIONS"
.PP
This program follows the usual
GNU
command line syntax, with long options starting with two dashes (\(oq\-\(cq)\&. A summary of options is included below\&.
.PP
\fB\-\-help\fR
.RS 4
Show summary of options\&.
.RE
.PP
\fB\-\-description\fR
.RS 4
Sets the profile description\&.
.RE
.PP
\fB\-\-copyright\fR
.RS 4
Sets the profile copyright\&.
.RE
.PP
\fB\-\-model\fR
.RS 4
Sets the profile model\&.
.RE
.PP
\fB\-\-manufacturer\fR
.RS 4
Sets the profile manufacturer\&.
.RE
.SH "AUTHOR"
.PP
This manual page was written by Richard Hughes
<richard@hughsie\&.com>\&.
