'\" t
.\"     Title: daxctl
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2019-03-18
.\"    Manual: daxctl Manual
.\"    Source: daxctl
.\"  Language: English
.\"
.TH "DAXCTL" "1" "2019-03-18" "daxctl" "daxctl Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
daxctl \- Provides enumeration and provisioning commands for the Linux kernel Device\-DAX facility
.SH "SYNOPSIS"
.sp
.nf
\fIdaxctl\fP [\-\-version] [\-\-help] COMMAND [ARGS]
.fi
.br
.SH "OPTIONS"
.sp
\-v, \-\-version
.RS 4
Display daxctl version.
.RE
.sp
\-h, \-\-help
.RS 4
Run daxctl help command.
.RE
.SH "DESCRIPTION"
.sp
The daxctl utility provides enumeration and provisioning commands for
the Linux kernel Device\-DAX facility. This facility enables DAX mappings
of performance / feature differentiated memory without need of a
filesystem.
.SH "COPYRIGHT"
.sp
Copyright (c) 2016 \- 2019, Intel Corporation. License GPLv2: GNU GPL
version 2 \c
.URL "http://gnu.org/licenses/gpl.html" "" "."
This is free software:
you are free to change and redistribute it.  There is NO WARRANTY, to
the extent permitted by law.
.SH "SEE ALSO"
.sp
ndctl\-create\-namespace(1),
ndctl\-list(1)