'\" t
.\"     Title: flatpak list
.\"    Author: Alexander Larsson <alexl@redhat.com>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 03/29/2019
.\"    Manual: flatpak list
.\"    Source: flatpak
.\"  Language: English
.\"
.TH "FLATPAK LIST" "1" "" "flatpak" "flatpak list"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
flatpak-list \- List installed applications and/or runtimes
.SH "SYNOPSIS"
.HP \w'\fBflatpak\ list\fR\ 'u
\fBflatpak list\fR [OPTION...]
.SH "DESCRIPTION"
.PP
Lists the names of the installed applications and runtimes\&.
.PP
By default, both apps and runtimes are shown, but you can change this by using the
\fB\-\-app\fR
or
\fB\-\-runtime\fR
options\&.
.PP
By default, both per\-user and system\-wide installations are shown\&. Use the
\fB\-\-user\fR,
\fB\-\-installation\fR
or
\fB\-\-system\fR
options to change this\&.
.PP
The list command can also be used to find installed apps that use a certain runtime, with the
\fB\-\-app\-runtime\fR
option\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show help options and exit\&.
.RE
.PP
\fB\-\-user\fR
.RS 4
List per\-user installations\&.
.RE
.PP
\fB\-\-system\fR
.RS 4
List the default system\-wide installations\&.
.RE
.PP
\fB\-\-installation=NAME\fR
.RS 4
List a system\-wide installation specified by
NAME
among those defined in
/etc/flatpak/installations\&.d/\&. Using
\fB\-\-installation=default\fR
is equivalent to using
\fB\-\-system\fR\&.
.RE
.PP
\fB\-\-arch=ARCH\fR
.RS 4
List installations for this architecture\&.
.RE
.PP
\fB\-d\fR, \fB\-\-show\-details\fR
.RS 4
Show origin, sizes and other extra information\&. Equivalent to
\fB\-\-columns=all\fR\&.
.RE
.PP
\fB\-\-app\fR
.RS 4
List applications\&.
.RE
.PP
\fB\-\-runtime\fR
.RS 4
List runtimes\&.
.RE
.PP
\fB\-\-all\fR, \fB\-a\fR
.RS 4
List all installed runtimes, including locale and debug extensions\&. These are hidden by default\&.
.RE
.PP
\fB\-\-app\-runtime=RUNTIME\fR
.RS 4
List applications that use the given runtime\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Print debug information during command processing\&.
.RE
.PP
\fB\-\-ostree\-verbose\fR
.RS 4
Print OSTree debug information during command processing\&.
.RE
.PP
\fB\-\-columns=FIELD,\&...\fR
.RS 4
Specify what information to show about each ref\&. You can list multiple fields, or use this option multiple times\&.
.sp
Append :s[tart], :m[iddle], :e[nd] or :f[ull] to column names to change ellipsization\&.
.RE
.SH "FIELDS"
.PP
The following fields are understood by the
\fB\-\-columns\fR
option:
.PP
description
.RS 4
Show the description
.RE
.PP
application
.RS 4
Show the application or runtime ID
.RE
.PP
arch
.RS 4
Show the architecture
.RE
.PP
branch
.RS 4
Show the branch
.RE
.PP
version
.RS 4
Show the version
.RE
.PP
ref
.RS 4
Show the ref
.RE
.PP
origin
.RS 4
Show the origin remote
.RE
.PP
installation
.RS 4
Show the installation
.RE
.PP
active
.RS 4
Show the active commit
.RE
.PP
latest
.RS 4
Show the latest commit
.RE
.PP
size
.RS 4
Show the installed size
.RE
.PP
options
.RS 4
Show options
.RE
.PP
all
.RS 4
Show all columns
.RE
.PP
help
.RS 4
Show the list of available columns
.RE
.PP
Note that field names can be abbreviated to a unique prefix\&.
.SH "EXAMPLES"
.PP
\fB$ flatpak \-\-user \-\-columns=app list\fR
.sp
.if n \{\
.RS 4
.\}
.nf
\fBApplication\fR
org\&.gnome\&.Builder
org\&.freedesktop\&.glxgears
org\&.gnome\&.MyApp
org\&.gnome\&.GEdit
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
\fBflatpak\fR(1),
\fBflatpak-install\fR(1),
\fBflatpak-update\fR(1)
