'\" t
.\"     Title: flatpak build-init
.\"    Author: Alexander Larsson <alexl@redhat.com>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 03/29/2019
.\"    Manual: flatpak build-init
.\"    Source: flatpak
.\"  Language: English
.\"
.TH "FLATPAK BUILD\-INIT" "1" "" "flatpak" "flatpak build-init"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
flatpak-build-init \- Initialize a build directory
.SH "SYNOPSIS"
.HP \w'\fBflatpak\ build\-init\fR\ 'u
\fBflatpak build\-init\fR [OPTION...] DIRECTORY APPNAME SDK RUNTIME [BRANCH]
.SH "DESCRIPTION"
.PP
Initializes a directory for building an application\&.
DIRECTORY
is the name of the directory\&.
APPNAME
is the application id of the app that will be built\&.
SDK
and
RUNTIME
specify the sdk and runtime that the application should be built against and run in\&.
.PP
The result of this command is that a
metadata
file is created inside the given directory\&. Additionally, empty
files
and
var
subdirectories are created\&.
.PP
It is an error to run build\-init on a directory that has already been initialized as a build directory\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show help options and exit\&.
.RE
.PP
\fB\-\-arch=ARCH\fR
.RS 4
The architecture to use\&.
.RE
.PP
\fB\-v\fR, \fB\-\-var=RUNTIME\fR
.RS 4
Initialize var from the named runtime\&.
.RE
.PP
\fB\-w\fR, \fB\-\-writable\-sdk\fR
.RS 4
Initialize /usr with a copy of the sdk, which is writable during flatpak build\&. This can be used if you need to install build tools in /usr during the build\&. This is stored in the
usr
subdirectory of the app dir, but will not be part of the final app\&.
.RE
.PP
\fB\-\-tag=TAG\fR
.RS 4
Add a tag to the metadata file\&. This option can be used multiple times\&.
.RE
.PP
\fB\-\-sdk\-extension=EXTENSION\fR
.RS 4
When using
\fB\-\-writable\-sdk\fR, in addition to the sdk, also install the specified extension\&. This option can be used multiple times\&.
.RE
.PP
\fB\-\-extension=NAME=VARIABLE[=VALUE]\fR
.RS 4
Add extension point info\&.
.RE
.PP
\fB\-\-sdk\-dir\fR
.RS 4
Specify a custom subdirectory to use instead of
usr
for
\fB\-\-writable\-sdk\fR\&.
.RE
.PP
\fB\-\-update\fR
.RS 4
Re\-initialize the sdk and var, don\*(Aqt fail if already initialized\&.
.RE
.PP
\fB\-\-base=APP\fR
.RS 4
Initialize the application with files from another specified application\&.
.RE
.PP
\fB\-\-base\-version=VERSION\fR
.RS 4
Specify the version to use for
\fB\-\-base\fR\&. If not specified, will default to "master"\&.
.RE
.PP
\fB\-\-base\-extension=EXTENSION\fR
.RS 4
When using
\fB\-\-base\fR, also install the specified extension from the app\&. This option can be used multiple times\&.
.RE
.PP
\fB\-\-type=TYPE\fR
.RS 4
This can be used to build different types of things\&. The default is "app" which is a regular app, but "runtime" creates a runtime based on an existing runtime, and "extension" creates an extension for an app or runtime\&.
.RE
.PP
\fB\-\-extension\-tag=EXTENSION_TAG\fR
.RS 4
If building an extension, the tag to use when searching for the mount point of the extension\&.
.RE
.PP
\fB\-\-verbose\fR
.RS 4
Print debug information during command processing\&.
.RE
.PP
\fB\-\-ostree\-verbose\fR
.RS 4
Print OSTree debug information during command processing\&.
.RE
.SH "EXAMPLES"
.PP
\fB$ flatpak build\-init /build/my\-app org\&.gnome\&.Sdk org\&.gnome\&.Platform 3\&.16\fR
.SH "SEE ALSO"
.PP
\fBflatpak\fR(1),
\fBflatpak-build\fR(1),
\fBflatpak-build-finish\fR(1),
\fBflatpak-build-export\fR(1)
