'\" t
.\"     Title: flatpak document-info
.\"    Author: Alexander Larsson <alexl@redhat.com>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 03/29/2019
.\"    Manual: flatpak document-info
.\"    Source: flatpak
.\"  Language: English
.\"
.TH "FLATPAK DOCUMENT\-IN" "1" "" "flatpak" "flatpak document-info"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
flatpak-document-info \- Show information about exported files
.SH "SYNOPSIS"
.HP \w'\fBflatpak\ document\-info\fR\ 'u
\fBflatpak document\-info\fR [OPTION...] FILE
.SH "DESCRIPTION"
.PP
Shows information about an exported file, such as the document id, the fuse path, the original location in the filesystem, and the per\-application permissions\&.
.PP
FILE
can either be a file in the fuse filesystem at
/run/user/$UID/doc/, or a file anywhere else\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show help options and exit\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Print debug information during command processing\&.
.RE
.PP
\fB\-\-ostree\-verbose\fR
.RS 4
Print OSTree debug information during command processing\&.
.RE
.SH "EXAMPLES"
.PP
\fB$ flatpak document\-info ~/Sources/gtk/gail\-3\&.0\&.pc\fR
.sp
.if n \{\
.RS 4
.\}
.nf
id: dd32c34a
path: /run/user/1000/doc/dd32c34a/gail\-3\&.0\&.pc
origin: /home/mclasen/Sources/gtk/gail\-3\&.0\&.pc
permissions:
        org\&.gnome\&.gedit read, write
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
\fBflatpak\fR(1),
\fBflatpak-document-export\fR(1),
\fBflatpak-document-unexport\fR(1),
\fBflatpak-documents\fR(1)
