'\" t
.\"     Title: flatpak remote-modify
.\"    Author: Alexander Larsson <alexl@redhat.com>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 03/29/2019
.\"    Manual: flatpak remote-modify
.\"    Source: flatpak
.\"  Language: English
.\"
.TH "FLATPAK REMOTE\-MODI" "1" "" "flatpak" "flatpak remote-modify"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
flatpak-remote-modify \- Modify a remote repository
.SH "SYNOPSIS"
.HP \w'\fBflatpak\ remote\-modify\fR\ 'u
\fBflatpak remote\-modify\fR [OPTION...] NAME
.SH "DESCRIPTION"
.PP
Modifies options for an existing remote repository in the flatpak repository configuration\&.
NAME
is the name for the remote\&.
.PP
Unless overridden with the
\fB\-\-system\fR,
\fB\-\-user\fR, or
\fB\-\-installation\fR
options, this command uses either the default system\-wide installation or the per\-user one, depending on which has the specified
REMOTE\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show help options and exit\&.
.RE
.PP
\fB\-\-user\fR
.RS 4
Modify the per\-user configuration\&.
.RE
.PP
\fB\-\-system\fR
.RS 4
Modify the default system\-wide configuration\&.
.RE
.PP
\fB\-\-installation=NAME\fR
.RS 4
Modify a system\-wide installation specified by
NAME
among those defined in
/etc/flatpak/installations\&.d/\&. Using
\fB\-\-installation=default\fR
is equivalent to using
\fB\-\-system\fR\&.
.RE
.PP
\fB\-\-no\-gpg\-verify\fR
.RS 4
Disable GPG verification for the added remote\&.
.RE
.PP
\fB\-\-gpg\-verify\fR
.RS 4
Enable GPG verification for the added remote\&.
.RE
.PP
\fB\-\-prio=PRIO\fR
.RS 4
Set the priority for the remote\&. Default is 1, higher is more prioritized\&. This is mainly used for graphical installation tools\&.
.RE
.PP
\fB\-\-no\-enumerate\fR
.RS 4
Mark the remote as not enumerated\&. This means the remote will not be used to list applications, for instance in graphical installation tools\&.
.RE
.PP
\fB\-\-no\-use\-for\-deps\fR
.RS 4
Mark the remote as not to be used for automatic runtime dependency resolution\&.
.RE
.PP
\fB\-\-disable\fR
.RS 4
Disable the remote\&. Disabled remotes will not be automatically updated from\&.
.RE
.PP
\fB\-\-enable\fR
.RS 4
Enable the remote\&.
.RE
.PP
\fB\-\-enumerate\fR
.RS 4
Mark the remote as enumerated\&. This means the remote will be used to list applications, for instance in graphical installation tools\&.
.RE
.PP
\fB\-\-use\-for\-deps\fR
.RS 4
Mark the remote as to be used for automatic runtime dependency resolution\&.
.RE
.PP
\fB\-\-title=TITLE\fR
.RS 4
A title for the remote, e\&.g\&. for display in a UI\&.
.RE
.PP
\fB\-\-default\-branch=BRANCH\fR
.RS 4
A default branch for the remote, mainly for use in a UI\&.
.RE
.PP
\fB\-\-collection\-id=COLLECTION\-ID\fR
.RS 4
The globally unique identifier of the remote repository, to allow mirrors to be grouped\&. This must only be set to the collection ID provided by the remote, and must not be set if the remote does not provide a collection ID\&.
.RE
.PP
\fB\-\-url=URL\fR
.RS 4
Set a new URL\&.
.RE
.PP
\fB\-\-update\-metadata\fR
.RS 4
Update the remote\*(Aqs extra metadata from the OSTree repository\*(Aqs summary file\&. Only xa\&.title and xa\&.default\-branch are supported at the moment\&.
.RE
.PP
\fB\-\-gpg\-import=FILE\fR
.RS 4
Import gpg keys from the specified keyring file as trusted for the new remote\&. If the file is \- the keyring is read from standard input\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Print debug information during command processing\&.
.RE
.PP
\fB\-\-ostree\-verbose\fR
.RS 4
Print OSTree debug information during command processing\&.
.RE
.SH "EXAMPLES"
.PP
\fB$ flatpak \-\-user remote\-modify \-\-no\-gpg\-verify test\-repo\fR
.SH "SEE ALSO"
.PP
\fBflatpak\fR(1),
\fBflatpak-remote-add\fR(1),
\fBflatpak-remote-delete\fR(1),
\fBflatpak-remotes\fR(1)
