'\" t
.\"     Title: flatpak build-import-bundle
.\"    Author: Alexander Larsson <alexl@redhat.com>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 03/29/2019
.\"    Manual: flatpak build-import-bundle
.\"    Source: flatpak
.\"  Language: English
.\"
.TH "FLATPAK BUILD\-IMPOR" "1" "" "flatpak" "flatpak build-import-bundle"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
flatpak-build-import-bundle \- Import a file bundle into a local repository
.SH "SYNOPSIS"
.HP \w'\fBflatpak\ build\-import\-bundle\fR\ 'u
\fBflatpak build\-import\-bundle\fR [OPTION...] LOCATION FILENAME
.SH "DESCRIPTION"
.PP
Imports a bundle from a file named
FILENAME
into the repository at
LOCATION\&.
.PP
The format of the bundle file is that generated by build\-bundle\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show help options and exit\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Print debug information during command processing\&.
.RE
.PP
\fB\-\-ostree\-verbose\fR
.RS 4
Print OSTree debug information during command processing\&.
.RE
.PP
\fB\-\-ref=REF\fR
.RS 4
Override the ref specified in the bundle\&.
.RE
.PP
\fB\-\-oci\fR
.RS 4
Import an OCI image instead of a Flatpak bundle\&.
.RE
.PP
\fB\-\-update\-appstream\fR
.RS 4
Update the appstream branch after the build\&.
.RE
.PP
\fB\-\-no\-update\-summary\fR
.RS 4
Don\*(Aqt update the summary file after the new commit is added\&. This means the repository will not be useful for serving over http until build\-update\-repo has been run\&. This is useful is you want to do multiple repo operations before finally updating the summary\&.
.RE
.PP
\fB\-\-gpg\-sign=KEYID\fR
.RS 4
Sign the commit with this GPG key\&. This option can be used multiple times\&.
.RE
.PP
\fB\-\-gpg\-homedir=PATH\fR
.RS 4
GPG Homedir to use when looking for keyrings
.RE
.SH "SEE ALSO"
.PP
\fBostree\fR(1),
\fBflatpak\fR(1),
\fBflatpak-build-bundle\fR(1),
\fBflatpak-build-update-repo\fR(1)
