'\" t
.\"     Title: flatpak build-update-repo
.\"    Author: Alexander Larsson <alexl@redhat.com>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 03/29/2019
.\"    Manual: flatpak build-update-repo
.\"    Source: flatpak
.\"  Language: English
.\"
.TH "FLATPAK BUILD\-UPDAT" "1" "" "flatpak" "flatpak build-update-repo"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
flatpak-build-update-repo \- Create a repository from a build directory
.SH "SYNOPSIS"
.HP \w'\fBflatpak\ build\-update\-repo\fR\ 'u
\fBflatpak build\-update\-repo\fR [OPTION...] LOCATION
.SH "DESCRIPTION"
.PP
Updates repository metadata for the repository at
LOCATION\&. This command generates an OSTree summary file that lists the contents of the repository\&. The summary is used by flatpak remote\-ls and other commands to display the contents of remote repositories\&.
.PP
After this command,
LOCATION
can be used as the repository location for flatpak remote\-add, either by exporting it over http, or directly with a file: url\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show help options and exit\&.
.RE
.PP
\fB\-\-redirect\-url=URL\fR
.RS 4
Redirect this repo to a new URL\&.
.RE
.PP
\fB\-\-title=TITLE\fR
.RS 4
A title for the repository, e\&.g\&. for display in a UI\&. The title is stored in the repository summary\&.
.RE
.PP
\fB\-\-default\-branch=BRANCH\fR
.RS 4
A default branch for the repository, mainly for use in a UI\&.
.RE
.PP
\fB\-\-gpg\-import=FILE\fR
.RS 4
Import a new default GPG public key from the given file\&.
.RE
.PP
\fB\-\-collection\-id=COLLECTION\-ID\fR
.RS 4
The globally unique identifier of the remote repository, to allow mirrors to be grouped\&. This must be set to a globally unique reverse DNS string if the repository is to be made publicly available\&. If a collection ID is already set on an existing repository, this will update it\&. If not specified, the existing collection ID will be left unchanged\&.
.RE
.PP
\fB\-\-deploy\-collection\-id\fR
.RS 4
Deploy the collection ID (set using
\fB\-\-collection\-id\fR) in the static remote configuration for all clients\&. This is irrevocable once published in a repository\&. Use it to decide when to roll out a collection ID to users of an existing repository\&. If constructing a new repository which has a collection ID, you should typically always pass this option\&.
.RE
.PP
\fB\-\-gpg\-sign=KEYID\fR
.RS 4
Sign the commit with this GPG key\&. This option can be used multiple times\&.
.RE
.PP
\fB\-\-gpg\-homedir=PATH\fR
.RS 4
GPG Homedir to use when looking for keyrings
.RE
.PP
\fB\-\-generate\-static\-deltas\fR
.RS 4
Generate static deltas for all references\&. This generates from\-empty and delta static files that allow for faster download\&.
.RE
.PP
\fB\-\-static\-delta\-jobs=NUM\-JOBS\fR
.RS 4
Limit the number of parallel jobs creating static deltas\&. The default is the number of cpus\&.
.RE
.PP
\fB\-\-static\-delta\-ignore\-ref=PATTERN\fR
.RS 4
Don\*(Aqt generate deltas for runtime or application id matching this pattern\&. For instance, \-\-static\-delta\-ignore\-ref=*\&.Sources means there will not be any deltas for source refs\&.
.RE
.PP
\fB\-\-prune\fR
.RS 4
Remove unreferenced objects in repo\&.
.RE
.PP
\fB\-\-prune\-depth\fR
.RS 4
Only keep at most this number of old versions for any particular ref\&. Default is \-1 which means infinite\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Print debug information during command processing\&.
.RE
.PP
\fB\-\-ostree\-verbose\fR
.RS 4
Print OSTree debug information during command processing\&.
.RE
.SH "SEE ALSO"
.PP
\fBostree\fR(1),
\fBflatpak\fR(1),
\fBflatpak-remote-ls\fR(1),
\fBflatpak-build-export\fR(1)
