'\" t
.\"     Title: flatpak update
.\"    Author: Alexander Larsson <alexl@redhat.com>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 03/29/2019
.\"    Manual: flatpak update
.\"    Source: flatpak
.\"  Language: English
.\"
.TH "FLATPAK UPDATE" "1" "" "flatpak" "flatpak update"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
flatpak-update \- Update an application or runtime
.SH "SYNOPSIS"
.HP \w'\fBflatpak\ update\fR\ 'u
\fBflatpak update\fR [OPTION...] [REF...]
.HP \w'\fBflatpak\ update\fR\ 'u
\fBflatpak update\fR [OPTION...] \-\-appstream [REMOTE]
.SH "DESCRIPTION"
.PP
Updates applications and runtimes\&.
REF
is a reference to the application or runtime to update\&. If no
REF
is given, everything is updated, as well as appstream info for all remotes\&.
.PP
Each
REF
argument is a full or partial indentifier in the flatpak ref format, which looks like "(app|runtime)/ID/ARCH/BRANCH"\&. All elements except ID are optional and can be left out, including the slashes, so most of the time you need only specify ID\&. Any part left out will be matched against what is installed, and if there are multiple matches an error message will list the alternatives\&.
.PP
By default this looks for both apps and runtimes with the given
REF, but you can limit this by using the
\fB\-\-app\fR
or
\fB\-\-runtime\fR
option, or by supplying the initial element in the
REF\&.
.PP
Normally, this command updates the application to the tip of its branch\&. But it is possible to check out another commit, with the \-\-commit option\&.
.PP
If the configured remote for a ref being updated has a collection ID configured on it, flatpak will search mounted filesystems such as USB drives as well as Avahi services advertised on the local network for the needed refs, in order to support offline updates\&. See
\fBostree-find-remotes\fR(1)
for more information\&.
.PP
Note that updating a runtime is different from installing a different branch, and runtime updates are expected to keep strict compatibility\&. If an application update does cause a problem, it is possible to go back to the previous version, with the
\fB\-\-commit\fR
option\&.
.PP
Unless overridden with the
\fB\-\-user\fR,
\fB\-\-system\fR
or
\fB\-\-installation\fR
option, this command updates any matching refs in the standard system\-wide installation and the per\-user one\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show help options and exit\&.
.RE
.PP
\fB\-\-user\fR
.RS 4
Update a per\-user installation\&.
.RE
.PP
\fB\-\-system\fR
.RS 4
Update the default system\-wide installation\&.
.RE
.PP
\fB\-\-installation=NAME\fR
.RS 4
Updates a system\-wide installation specified by
NAME
among those defined in
/etc/flatpak/installations\&.d/\&. Using
\fB\-\-installation=default\fR
is equivalent to using
\fB\-\-system\fR\&.
.RE
.PP
\fB\-\-arch=ARCH\fR
.RS 4
The architecture to update for\&.
.RE
.PP
\fB\-\-subpath=PATH\fR
.RS 4
Install only a subpath of the ref\&. This is mainly used to install a subset of locales\&. This can be added multiple times to install multiple subpaths\&. If this is not specified the subpaths specified at install time are reused\&.
.RE
.PP
\fB\-\-commit=COMMIT\fR
.RS 4
Update to this commit, instead of the tip of the branch\&. You can find commits using
\fBflatpak remote\-info \-\-log REMOTE REF\fR\&.
.RE
.PP
\fB\-\-no\-deploy\fR
.RS 4
Download the latest version, but don\*(Aqt deploy it\&.
.RE
.PP
\fB\-\-no\-pull\fR
.RS 4
Don\*(Aqt download the latest version, deploy whatever is locally available\&.
.RE
.PP
\fB\-\-no\-related\fR
.RS 4
Don\*(Aqt download related extensions, such as the locale data\&.
.RE
.PP
\fB\-\-no\-deps\fR
.RS 4
Don\*(Aqt update or install runtime dependencies when installing\&.
.RE
.PP
\fB\-\-app\fR
.RS 4
Only look for an app with the given name\&.
.RE
.PP
\fB\-\-appstream\fR
.RS 4
Update appstream for
REMOTE, or all remotes if no remote is specified\&.
.RE
.PP
\fB\-\-runtime\fR
.RS 4
Only look for a runtime with the given name\&.
.RE
.PP
\fB\-y\fR, \fB\-\-assumeyes\fR
.RS 4
Automatically answer yes to all questions (or pick the most prioritized answer)\&. This is useful for automation\&.
.RE
.PP
\fB\-\-noninteractive\fR
.RS 4
Produce minimal output and avoid most questions\&. This is suitable for use in non\-interactive situations, e\&.g\&. in a build script\&.
.RE
.PP
\fB\-\-force\-remove\fR
.RS 4
Remove old files even if they\*(Aqre in use by a running application\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Print debug information during command processing\&.
.RE
.PP
\fB\-\-ostree\-verbose\fR
.RS 4
Print OSTree debug information during command processing\&.
.RE
.SH "EXAMPLES"
.PP
\fB$ flatpak \-\-user update org\&.gnome\&.GEdit\fR
.SH "SEE ALSO"
.PP
\fBflatpak\fR(1),
\fBflatpak-install\fR(1),
\fBflatpak-list\fR(1),
\fBostree-find-remotes\fR(1)
