'\" t
.\"     Title: gnome-keyring-daemon
.\"    Author: Stef Walter <stefw@redhat.com>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 03/15/2019
.\"    Manual: User Commands
.\"    Source: gnome-keyring
.\"  Language: English
.\"
.TH "GNOME\-KEYRING\-DAEM" "1" "" "gnome-keyring" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gnome-keyring-daemon \- The gnome\-keyring daemon
.SH "SYNOPSIS"
.HP \w'\fBgnome\-keyring\-daemon\fR\ 'u
\fBgnome\-keyring\-daemon\fR [OPTION...]
.SH "DESCRIPTION"
.PP
The
\fBgnome\-keyring\-daemon\fR
is a service that stores your passwords and secrets\&. It is normally started automatically when a user logs into a desktop session\&.
.PP
The
\fBgnome\-keyring\-daemon\fR
implements the DBus Secret Service API, and you can use tools like
\fBseahorse\fR
or
\fBsecret\-tool\fR
to interact with it\&.
.PP
The daemon also implements a GnuPG and SSH agent both of which automatically load the user\*(Aqs keys, and prompt for passwords when necessary\&.
.PP
The daemon will print out various environment variables which should be set in the user\*(Aqs environment, in order to interact with the daemon\&.
.SH "OPTIONS"
.PP
The various startup arguments below can be used:
.PP
\fB\-c\fR, \fB\-\-components=\fR\fB\fIssh,secrets,pkcs11\fR\fR
.RS 4
Ask the daemon to only initialize certain components\&. Valid components are
ssh,
secrets,
pkcs11\&.
.sp
By default all components are initialized\&.
.RE
.PP
\fB\-C\fR, \fB\-\-control\-directory=\fR\fB\fI/path/to/directory\fR\fR
.RS 4
Use this directory for creating communication sockets\&. By default a temporary directory is automatically created\&.
.RE
.PP
\fB\-d\fR, \fB\-\-daemonize\fR
.RS 4
Run as a real daemon, disconnected from the terminal\&.
.RE
.PP
\fB\-f\fR, \fB\-\-foreground\fR
.RS 4
Run in the foreground, and do not fork or become a daemon\&.
.RE
.PP
\fB\-l\fR, \fB\-\-login\fR
.RS 4
This argument tells the daemon it is being run by PAM\&. It reads all of stdin (including any newlines) as a login password and does not complete actual initialization\&.
.sp
The daemon should later be initialized with a
\fBgnome\-keyring\-daemon\fR\ \&\fB\-\-start\fR
invocation\&.
.sp
This option implies
\fB\-\-unlock\fR\&. It may not be used together with either the
\fB\-\-replace\fR
or
\fB\-\-start\fR
arguments\&.
.RE
.PP
\fB\-r\fR, \fB\-\-replace\fR
.RS 4
Try to replace a running keyring daemon, and assume its environment variables\&. A successful replacement depends on the
GNOME_KEYRING_CONTROL
environment variable being set by an earlier daemon\&.
.sp
This option may not be used together with either the
\fB\-\-login\fR
or
\fB\-\-start\fR
arguments\&.
.RE
.PP
\fB\-s\fR, \fB\-\-start\fR
.RS 4
Connect to an already running daemon and initialize it\&. This is often used to complete initialization of a daemon that was started by PAM using the
\fB\-\-login\fR
argument\&.
.sp
This option may not be used together with either the
\fB\-\-login\fR
or
\fB\-\-replace\fR
arguments\&.
.RE
.PP
\fB\-\-unlock\fR
.RS 4
Read a password from stdin, and use it to unlock the login keyring or create it if the login keyring does not exist\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Print out the gnome\-keyring version and then exit\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show help options and exit\&.
.RE
.SH "BUGS"
.PP
Please send bug reports to either the distribution bug tracker or the upstream bug tracker at
\m[blue]\fBhttps://bugzilla\&.gnome\&.org/enter_bug\&.cgi?product=gnome\-keyring\fR\m[]
.SH "SEE ALSO"
\fBsecret-tool\fR(1), \fBseahorse\fR(1)
.PP
Further details available in the gnome\-keyring online documentation at
\m[blue]\fBhttps://wiki\&.gnome\&.org/GnomeKeyring\fR\m[]
and in the secret\-service online documentation at
\m[blue]\fBhttp://standards\&.freedesktop\&.org/secret\-service/\fR\m[]
