'\" t
.\"     Title: ndctl
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2019-03-18
.\"    Manual: ndctl Manual
.\"    Source: ndctl
.\"  Language: English
.\"
.TH "NDCTL" "1" "2019-03-18" "ndctl" "ndctl Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
ndctl \- Manage "libnvdimm" subsystem devices (Non\-volatile Memory)
.SH "SYNOPSIS"
.sp
.nf
\fIndctl\fP [\-\-version] [\-\-help] [OPTIONS] COMMAND [ARGS]
.fi
.br
.SH "OPTIONS"
.sp
\-v, \-\-version
.RS 4
Display ndctl version.
.RE
.sp
\-h, \-\-help
.RS 4
Run ndctl help command.
.RE
.SH "DESCRIPTION"
.sp
ndctl is utility for managing the "libnvdimm" kernel subsystem.
The "libnvdimm" subsystem defines a kernel device model and control
message interface for platform NVDIMM resources like those defined by
the ACPI 6.0 NFIT (NVDIMM Firmware Interface Table).  Operations
supported by the tool include, provisioning capacity (namespaces), as
well as enumerating/enabling/disabling the devices (dimms, regions,
namspaces) associated with an NVDIMM bus.
.SH "COPYRIGHT"
.sp
Copyright (c) 2016 \- 2019, Intel Corporation. License GPLv2: GNU GPL
version 2 \c
.URL "http://gnu.org/licenses/gpl.html" "" "."
This is free software:
you are free to change and redistribute it.  There is NO WARRANTY, to
the extent permitted by law.
.SH "SEE ALSO"
.sp
ndctl\-create\-namespace(1),
ndctl\-destroy\-namespace(1),
ndctl\-check\-namespace(1),
ndctl\-enable\-region(1),
ndctl\-disable\-region(1),
ndctl\-enable\-dimm(1),
ndctl\-disable\-dimm(1),
ndctl\-enable\-namespace(1),
ndctl\-disable\-namespace(1),
ndctl\-zero\-labels(1),
ndctl\-read\-labels(1),
ndctl\-inject\-error(1),
ndctl\-list(1),
\c
.URL "https://www.kernel.org/doc/Documentation/nvdimm/nvdimm.txt" "LIBNVDIMM
Overview" ,
\c
.URL "http://pmem.io/documents/NVDIMM_Driver_Writers_Guide.pdf" "NVDIMM Driver
Writer\(cqs Guide"