'\" t
.\"     Title: ndctl-write-labels
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2019-03-18
.\"    Manual: ndctl Manual
.\"    Source: ndctl
.\"  Language: English
.\"
.TH "NDCTL\-WRITE\-LABELS" "1" "2019-03-18" "ndctl" "ndctl Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
ndctl\-write\-labels \- write data to the label area on a dimm
.SH "SYNOPSIS"
.sp
.nf
\fIndctl write\-labels <nmem> [\-i <filename>]\fP
.fi
.br
.SH "DESCRIPTION"
.sp
The namespace label area is a small persistent partition of capacity
available on some NVDIMM devices.  The label area is used to resolve
aliasing between \fIpmem\fP and \fIblk\fP capacity by delineating namespace
boundaries.
Read data from the input filename, or stdin, and write it to the given
<nmem> device. Note that the device must not be active in any region,
otherwise the kernel will not allow write access to the device\(cqs label
data area.
.SH "OPTIONS"
.sp
<memory device(s)>
.RS 4
One or more \fInmemX\fP device names. The keyword \fIall\fP can be specified to
operate on every dimm in the system, optionally filtered by bus id (see
\-\-bus= option).
.RE
.sp
\-b, \-\-bus=
.RS 4
Limit operation to memory devices (dimms) that are on the given bus.
Where \fIbus\fP can be a provider name or a bus id number.
.RE
.sp
\-v
.RS 4
Turn on verbose debug messages in the library (if ndctl was built with
logging and debug enabled).
.RE
.sp
\-i, \-\-input
.RS 4
input file
.RE
.SH "SEE ALSO"
.sp
.URL "http://www.uefi.org/sites/default/files/resources/UEFI_Spec_2_7.pdf" "UEFI NVDIMM Label Protocol" ""