'\" t
.\"     Title: ostree create-usb
.\"    Author: Matthew Leeds <matthew.leeds@endlessm.com>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 01/15/2019
.\"    Manual: ostree create-usb
.\"    Source: OSTree
.\"  Language: English
.\"
.TH "OSTREE CREATE\-USB" "1" "" "OSTree" "ostree create-usb"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ostree-create-usb \- Put the given refs on an external drive for P2P distribution\&.
.SH "SYNOPSIS"
.HP \w'\fBostree\ create\-usb\fR\ 'u
\fBostree create\-usb\fR [OPTIONS...] {MOUNT\-PATH} {COLLECTION\-ID\ REF} [COLLECTION\-ID\ REF...]
.SH "DESCRIPTION"
.PP
This command creates a repository in MOUNT\-PATH and pulls the given REF(s) into it so they can be found and pulled from (perhaps by another computer that\*(Aqs offline)\&. See
\fBostree-find-remotes\fR(1)
for more information on P2P distribution\&.
.PP
In order for ostree to pull refs from a mounted filesystem (such as a USB drive) the repo must be in a standard location\&. Specifically, subdirectories of
\&.ostree/repos\&.d
are checked, then
\&.ostree/repo,
ostree/repo, and
var/lib/flatpak/repo
are checked\&. By default
\fBostree create\-usb\fR
uses
\&.ostree/repo, but if you specify another location using
\fB\-\-destination\-repo\fR
a symbolic link will be created for you in
\&.ostree/repos\&.d\&.
.PP
This command will regenerate the
summary
file in the destination repo so that it stays accurate, so you shouldn\*(Aqt try to use summary signatures in the destination repo\&. This shouldn\*(Aqt be a concern because clients that support pulling from USB mounts use signed per\-repo and per\-commit metadata instead of summary signatures\&.
.SH "OPTIONS"
.PP
\fB\-\-disable\-fsync\fR
.RS 4
Do not invoke fsync()\&.
.RE
.PP
\fB\-\-destination\-repo\fR=DEST
.RS 4
Create the repository in DEST under MOUNT\-PATH, rather than the default location\&.
.RE
.PP
\fB\-\-commit\fR=COMMIT
.RS 4
Pull COMMIT instead of whatever REF points to\&. This can only be used if a single ref is specified\&.
.RE
.SH "EXAMPLE"
.PP
\fBostree \-\-repo=/var/lib/flatpak/repo create\-usb /run/media/mwleeds/f6d04c7a\-60f6\-4ba3\-bb96\-0f40498675be com\&.exampleos\&.Apps app/org\&.kde\&.Khangman/x86_64/stable com\&.exampleos\&.Apps ostree\-metadata com\&.exampleos\&.Apps appstream/x86_64\fR
.sp
.if n \{\
.RS 4
.\}
.nf

5 metadata, 213 content objects imported; 1 KiB transferred in 1 seconds                                                                                                                      Copied 3/3 refs successfully from \(oq/var/lib/flatpak/repo\(cq to \(oq\&.ostree/repo\(cq repository in \(oq/run/media/mwleeds/f6d04c7a\-60f6\-4ba3\-bb96\-0f40498675be\(cq\&.

.fi
.if n \{\
.RE
.\}
