'\" t
.\"     Title: ostree summary
.\"    Author: Colin Walters <walters@verbum.org>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 01/15/2019
.\"    Manual: ostree summary
.\"    Source: OSTree
.\"  Language: English
.\"
.TH "OSTREE SUMMARY" "1" "" "OSTree" "ostree summary"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ostree-summary \- Regenerate or view the summary metadata file
.SH "SYNOPSIS"
.HP \w'\fBostree\ summary\fR\ 'u
\fBostree summary\fR [\-\-gpg\-sign=KEYID] [\-\-gpg\-homedir=HOMEDIR] {\-\-update} [\-\-add\-metadata=\fIKEY\fR=\fIVALUE\fR...]
.HP \w'\fBostree\ summary\fR\ 'u
\fBostree summary\fR {\-\-view | \-\-raw}
.SH "DESCRIPTION"
.PP
The
summary
file is an optional higher level form of repository metadata that describes the available branches\&. It needs to be manually regenerated after a series of commits\&. Among other things, this allows atomically updating multiple commits\&.
.SH "OPTIONS"
.PP
\fB\-\-update\fR,\fB\-u\fR
.RS 4
Update the summary file\&. This option can be combined with
\fB\-\-add\-metadata\fR
to add metadata fields to the summary\&.
.sp
If the repository has a collection ID configured, the
ostree\-metadata
branch for that collection ID will also be updated with a new commit containing the given metadata, which will be signed if the summary file is signed\&.
.RE
.PP
\fB\-\-add\-metadata\fR,\fB\-m\fR=KEY=VALUE
.RS 4
Specify an additional metadata field to add to the summary\&. It must be in the format
\fB\fIKEY\fR\fR\fB=\fR\fB\fIVALUE\fR\fR
or as two separate arguments\&. The keys must be namespaced for your organisation or repository using a dot prefix\&. The values must be in GVariant text format\&. For example,
\fBexampleos\&.end\-of\-life "@t 1445385600"\fR\&. This option can be used multiple times\&.
.RE
.PP
\fB\-\-view\fR,\fB\-v\fR
.RS 4
View the contents of the summary file in a human readable format\&.
.RE
.PP
\fB\-\-raw\fR
.RS 4
View the raw bytes of the summary file\&.
.RE
.PP
\fB\-\-gpg\-sign\fR=KEYID
.RS 4
GPG Key ID to sign the summary with\&.
.RE
.PP
\fB\-\-gpg\-homedir\fR=HOMEDIR
.RS 4
GPG Homedir to use when looking for keyrings\&.
.RE
.SH "EXAMPLES"
.PP
\fB$ ostree summary \-u\fR
.PP
\fB$ ostree summary \-u \-m key="\*(Aqvalue\*(Aq"\fR
.PP
\fB$ ostree summary \-v\fR
.sp
.if n \{\
.RS 4
.\}
.nf
* ostree/1/1/0
    Latest Commit (4\&.2 MB):
      9828ab80f357459b4ab50f0629beab2ae3b67318fc3d161d10a89fae353afa90
    Timestamp (ostree\&.commit\&.timestamp): 2017\-11\-21T01:41:10\-08

Last\-Modified (ostree\&.summary\&.last\-modified): 2018\-01\-12T22:06:38\-08
.fi
.if n \{\
.RE
.\}
