.TH pipewire-monitor 1 User Manuals
.SH NAME
pipewire-monitor \- The PipeWire monitor
.SH SYNOPSIS
\fBpipewire-monitor [\fIremote-name\fB]
\f1
.SH DESCRIPTION
Monitor objects on the PipeWire instance.
.SH OPTIONS
.TP
\fBremote-name\f1
The name the remote instance to monitor. If left unspecified, a connection is made to the default PipeWire instance.
.TP
\fB-h | --help\f1
Show help.
.TP
\fB--version\f1
Show version information.
.SH AUTHORS
The PipeWire Developers <https://github.com/PipeWire/pipewire/issues>; PipeWire is available from \fBhttp://pipewire.org\f1
.SH SEE ALSO
\fBpipewire(1)\f1, 
