'\" t
.\"     Title: polkitd
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: May 2009
.\"    Manual: polkitd
.\"    Source: polkit
.\"  Language: English
.\"
.TH "POLKITD" "8" "May 2009" "polkit" "polkitd"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
polkitd \- The polkit system daemon
.SH "SYNOPSIS"
.HP \w'\fBpolkitd\fR\ 'u
\fBpolkitd\fR
.SH "DESCRIPTION"
.PP
\fBpolkitd\fR
provides the
\fIorg\&.freedesktop\&.PolicyKit1\fR
D\-Bus service on the system message bus\&. Users or administrators should never need to start this daemon as it will be automatically started by
\fBdbus-daemon\fR(1)
or
\fBsystemd\fR(1)
whenever an application calls into the service\&.
.PP
\fBpolkitd\fR
must be started with superuser privileges but drops privileges early by switching to the unprivileged
\fIpolkitd\fR
system user\&.
.PP
See the
\fBpolkit\fR(8)
man page for more information\&.
.SH "AUTHOR"
.PP
Written by David Zeuthen
<davidz@redhat\&.com>
with a lot of help from many others\&.
.SH "BUGS"
.PP
Please send bug reports to either the distribution or the polkit\-devel mailing list, see the link
\m[blue]\fB\%http://lists.freedesktop.org/mailman/listinfo/polkit-devel\fR\m[]
on how to subscribe\&.
.SH "SEE ALSO"
.PP
\fBpolkit\fR(8),
\fBpkaction\fR(1),
\fBpkcheck\fR(1),
\fBpkexec\fR(1),
\fBpkttyagent\fR(1),
\fBdbus-daemon\fR(1),
\fBsystemd\fR(1)
