# alacritty
# Autogenerated from man page manpages/alacritty.1
complete -c alacritty -l class --description 'Defines the window class on X11 [default: Alacritty].'
complete -c alacritty -s e -l command --description 'Command and args to execute (must be last argument) .'
complete -c alacritty -s t -l title --description 'Defines the window title [default: Alacritty].'

