# augenrules
# Autogenerated from man page manpages/augenrules.8
complete -c augenrules -l check --description 'test if rules have changed and need updating without overwriting audit. rules.'
complete -c augenrules -l load --description 'load old or newly built rules into the kernel.'

