# aulastlog
# Autogenerated from man page manpages/aulastlog.8
complete -c aulastlog -s u -l user --description 'Print the lastlog record for user with specified LOGIN only.'
complete -c aulastlog -l stdin --description 'Use stdin as the source of audit records.'

