# ausyscall
# Autogenerated from man page manpages/ausyscall.8
complete -c ausyscall -l dump --description 'Print all syscalls for the given arch.'
complete -c ausyscall -s a -s S -s F -o EPERM -s k --description '.'
complete -c ausyscall -l exact --description 'Instead of doing a partial word match, match the given syscall name exactly.'

