# autopoint
# Autogenerated from man page manpages/autopoint.1
complete -c autopoint -l help --description 'print this help and exit.'
complete -c autopoint -l version --description 'print version information and exit.'
complete -c autopoint -s f -l force --description 'force overwriting of files that already exist.'
complete -c autopoint -s n -l dry-run --description 'print modifications but don\'t perform them AUTHOR Written by Bruno Haible REP…'

