# avahi-set-host-name
# Autogenerated from man page manpages/avahi-set-host-name.1
complete -c avahi-set-host-name -s v -l verbose --description 'Enable verbose mode.'
complete -c avahi-set-host-name -s h -l help --description 'Show help.'
complete -c avahi-set-host-name -s V -l version --description 'Show version information.'

