# blkmapd
# Autogenerated from man page manpages/blkmapd.8
complete -c blkmapd -s h --description 'Display usage message.'
complete -c blkmapd -s d --description 'Performs device discovery only then exits.'
complete -c blkmapd -s f --description 'Runs blkmapd in the foreground and sends output to stderr (as opposed to sysl…'

