# btrfs-rescue
# Autogenerated from man page manpages/btrfs-rescue.8
complete -c btrfs-rescue -s y --description '.'
complete -c btrfs-rescue -s v --description '.'
complete -c btrfs-rescue -s h --description '.'

