# btrfs-select-super
# Autogenerated from man page manpages/btrfs-select-super.8
complete -c btrfs-select-super -s s -l super --description 'use \\*(Aqsuperblock\\(cqth superblock copy, valid values are 0 1 or 2 if the r…'

