# btrfs-receive
# Autogenerated from man page manpages/btrfs-receive.8
complete -c btrfs-receive -s v --description '.'
complete -c btrfs-receive -s f --description '.'
complete -c btrfs-receive -s C -l chroot --description '.'
complete -c btrfs-receive -s e --description '.'
complete -c btrfs-receive -s E -l max-errors --description '.'
complete -c btrfs-receive -s m --description '.'
complete -c btrfs-receive -l dump --description '.'

