# cd-fix-profile
# Autogenerated from man page manpages/cd-fix-profile.1
complete -c cd-fix-profile -l help --description 'Show summary of options.'
complete -c cd-fix-profile -l description --description 'Sets the profile description.'
complete -c cd-fix-profile -l copyright --description 'Sets the profile copyright.'
complete -c cd-fix-profile -l model --description 'Sets the profile model.'
complete -c cd-fix-profile -l manufacturer --description 'Sets the profile manufacturer.'

