# cert-to-efi-hash-list
# Autogenerated from man page manpages/cert-to-efi-hash-list.1
complete -c cert-to-efi-hash-list -s g --description 'Use <guid> as the owner of the signature.'
complete -c cert-to-efi-hash-list -s s --description 'Use SHA<hash> hash algorithm (256, 384, 512).'
complete -c cert-to-efi-hash-list -s t --description 'Time of Revocation for hash signature.'

