# certtool
# Autogenerated from man page manpages/certtool.1
complete -c certtool -l generate-privkey -l generate-dh-params --description '.'
complete -c certtool -l load-ca-certificate --description '$ certtool --load-ca-certificate ca. pem    --load-certificate cert.'

