# chcp
# Autogenerated from man page manpages/chcp.8
complete -c chcp -s h -l help --description 'Display help message and exit.'
complete -c chcp -s V -l version --description 'Display version and exit.'

