# cifscreds
# Autogenerated from man page manpages/cifscreds.1
complete -c cifscreds -s d -l domain --description 'The provided host/domain argument is a NT domainname.'
complete -c cifscreds -s u -l username --description 'Ordinarily, the username is derived from the unix username of the user adding…'

