# colrm
# Autogenerated from man page manpages/colrm.1
complete -c colrm -s V -l version --description 'Display version information and exit.'
complete -c colrm -s h -l help --description 'Display help text and exit.'

