# cvt
# Autogenerated from man page manpages/cvt.1
complete -c cvt -s v -l verbose --description 'Warn verbosely when a given mode does not completely correspond with CVT stan…'
complete -c cvt -s r -l reduced --description 'Create a mode with reduced blanking.'

