# daxctl-list
# Autogenerated from man page manpages/daxctl-list.1
complete -c daxctl-list -s r -l region --description '.'
complete -c daxctl-list -s d -l dev --description '.'
complete -c daxctl-list -s D -l devices --description '.'
complete -c daxctl-list -s R -l regions --description '.'
complete -c daxctl-list -s i -l idle --description '.'
complete -c daxctl-list -s u -l human --description '.'

