# dbus-uuidgen
# Autogenerated from man page manpages/dbus-uuidgen.1
complete -c dbus-uuidgen -l get --description 'If a filename is not given, defaults to localstatedir/lib/dbus/machine-id (lo…'
complete -c dbus-uuidgen -l ensure --description 'If a filename is not given, defaults to localstatedir/lib/dbus/machine-id (lo…'
complete -c dbus-uuidgen -l version --description 'Print the version of dbus-uuidgen.'

