# dd
# Autogenerated from man page manpages/dd.1
complete -c dd -l help --description 'display this help and exit.'
complete -c dd -l version --description 'output version information and exit AUTHOR Written by Paul Rubin, David MacKe…'

