# devlink-region
# Autogenerated from man page manpages/devlink-region.8
complete -c devlink-region -s V --description '.'
complete -c devlink-region -s n --description 'devlink region show [  DEV/REGION  ] devlink region del  DEV/REGION  snapshot…'

