# devlink-resource
# Autogenerated from man page manpages/devlink-resource.8
complete -c devlink-resource -s v --description 'devlink resource show DEV devlink resource help devlink resource set DEV path…'

