# devlink-port
# Autogenerated from man page manpages/devlink-port.8
complete -c devlink-port -s V --description '.'
complete -c devlink-port -s n --description 'devlink port set  DEV/PORT_INDEX [  type  {  eth  |  ib  |  auto  } ] devlink…'

