# devlink-dev
# Autogenerated from man page manpages/devlink-dev.8
complete -c devlink-dev -s V --description '.'
complete -c devlink-dev -s n --description 'devlink dev show [  DEV  ] devlink dev help devlink dev eswitch set DEV [  mo…'

