# dirname
# Autogenerated from man page manpages/dirname.1
complete -c dirname -s z -l zero --description 'end each output line with NUL, not newline.'
complete -c dirname -l help --description 'display this help and exit.'
complete -c dirname -l version --description 'output version information and exit EXAMPLES.'
complete -c dirname -s '>' --description '.'

