# dm-tool
# Autogenerated from man page manpages/dm-tool.1
complete -c dm-tool -s h -l help --description 'Show help options.'
complete -c dm-tool -l version --description 'Show release version.'
complete -c dm-tool -l session-bus --description 'Attempt to connect to the display manager using the session bus.'

