# dosfslabel
# Autogenerated from man page manpages/dosfslabel.8
complete -c dosfslabel -s h -l help --description 'Displays a help message.'
complete -c dosfslabel -s V -l version --description 'Shows version.'

