# dumpseg
# Autogenerated from man page manpages/dumpseg.8
complete -c dumpseg -s h -l help --description 'Display help message and exit.'
complete -c dumpseg -s V -l version --description 'Display version and exit.'

