# dumpexfat
# Autogenerated from man page manpages/dumpexfat.8
complete -c dumpexfat -s s --description 'Dump only info from super block.'
complete -c dumpexfat -s u --description 'Dump ranges of used sectors starting from 0 and separated with spaces.'
complete -c dumpexfat -s f --description 'Print out a list of fragments that compose the given file.'
complete -c dumpexfat -s V --description 'Print version and copyright.'

