# e4defrag
# Autogenerated from man page manpages/e4defrag.8
complete -c e4defrag -s c --description 'Get a current fragmentation count and an ideal fragmentation count, and calcu…'
complete -c e4defrag -s v --description 'option, the current fragmentation count and the ideal fragmentation count are…'

