# ecryptfs-migrate-home
# Autogenerated from man page manpages/ecryptfs-migrate-home.8
complete -c ecryptfs-migrate-home -s u -l user --description 'Migrate USER\'s home directory to an encrypted home directory.'

