# envsubst
# Autogenerated from man page manpages/envsubst.1
complete -c envsubst -s v -l variables --description 'output the variables occurring in SHELL-FORMAT . SS "Informative output:".'
complete -c envsubst -s h -l help --description 'display this help and exit.'
complete -c envsubst -s V -l version --description 'output version information and exit.'

