# eqn2graph
# Autogenerated from man page manpages/eqn2graph.1
complete -c eqn2graph -o unsafe --description 'Run  groff (1) in the `unsafe\' mode enabling the PIC macro  sh to execute arb…'
complete -c eqn2graph -o format --description 'Specify an output format; the default is PNG (Portable Network Graphics).'

