# ex
# Autogenerated from man page manpages/ex.1
complete -c ex -o ccommand --description 'Execute  command when editing begins.'
complete -c ex -s l --description 'Start in a special mode useful for the  Lisp programming language.'
complete -c ex -s r -s L --description 'When no argument is supplied with this option, all files to be recovered are …'
complete -c ex -s R --description 'Files are opened read-only when this option is given.'
complete -c ex -s s --description 'Script mode; all feedback for interactive editing is disabled.'
complete -c ex -s t --description 'Read the  tags file, then choose the file and position specified by  tagstrin…'
complete -c ex -s v --description 'Start in visual mode even if called as R ex .'
complete -c ex -s V --description 'Echo command input to standard error, unless it originates from a terminal.'
complete -c ex -s w --description 'Specify the size of the editing window for visual mode. \\"	from ex.'
complete -c ex -s c --description 'Execute command when editing begins.'

