# exo-csource
# Autogenerated from man page manpages/exo-csource.1
complete -c exo-csource -l build-list --description 'option, a list of (name, file) pairs to generate code for a list of images in…'
complete -c exo-csource -s h -l help --description '.'
complete -c exo-csource -s v -l version --description '.'
complete -c exo-csource -l extern --description '.'
complete -c exo-csource -l static --description '.'
complete -c exo-csource -l name --description '.'
complete -c exo-csource -l output --description '.'

