# exo-open
# Autogenerated from man page manpages/exo-open.1
complete -c exo-open -l launch --description 'tries to launch the preferred application for a certain category, optionally …'
complete -c exo-open -s '?' -l help --description '.'
complete -c exo-open -s v -l version --description '.'
complete -c exo-open -l working-directory --description '.'

