# expr
# Autogenerated from man page manpages/expr.1
complete -c expr -l help --description 'display this help and exit.'
complete -c expr -l version --description 'output version information and exit .'

