# extract_dca
# Autogenerated from man page manpages/extract_dca.1
complete -c extract_dca -s h --description 'display help.'
complete -c extract_dca -s s --description 'set track number (0-7 or 0x80-0x87).'
complete -c extract_dca -s t --description 'use transport stream demultiplexer, pid 0x10-0x1ffe AUTHORS Michel Lespinasse…'

