# factor
# Autogenerated from man page manpages/factor.1
complete -c factor -l help --description 'display this help and exit.'
complete -c factor -l version --description 'output version information and exit AUTHOR Written by Paul Rubin, Torbjorn Gr…'

