# fc-cat
# Autogenerated from man page manpages/fc-cat.1
complete -c fc-cat -s r -l recurse --description 'Recurse into subdirectories.'
complete -c fc-cat -s v -l verbose --description 'Be verbose.'
complete -c fc-cat -s h -l help --description 'Show summary of options.'

