# fc-scan
# Autogenerated from man page manpages/fc-scan.1
complete -c fc-scan -s f -l format --description 'Format output according to the format specifier format.'
complete -c fc-scan -s V -l version --description 'Show version of the program and exit.'
complete -c fc-scan -s h -l help --description 'Show summary of options.'

