# flatpak-permissions
# Autogenerated from man page manpages/flatpak-permissions.1
complete -c flatpak-permissions -s h -l help --description 'Show help options and exit.'
complete -c flatpak-permissions -s v -l verbose --description 'Print debug information during command processing.'
complete -c flatpak-permissions -l ostree-verbose --description 'Print OSTree debug information during command processing.'

