# flatpak-kill
# Autogenerated from man page manpages/flatpak-kill.1
complete -c flatpak-kill -s h -l help --description 'Show help options and exit.'
complete -c flatpak-kill -s v -l verbose --description 'Print debug information during command processing.'
complete -c flatpak-kill -l ostree-verbose --description 'Print OSTree debug information during command processing.'

