# flatpak-permission-reset
# Autogenerated from man page manpages/flatpak-permission-reset.1
complete -c flatpak-permission-reset -s h -l help --description 'Show help options and exit.'
complete -c flatpak-permission-reset -s v -l verbose --description 'Print debug information during command processing.'
complete -c flatpak-permission-reset -l ostree-verbose --description 'Print OSTree debug information during command processing.'

