# flatpak-remote-add
# Autogenerated from man page manpages/flatpak-remote-add.1
complete -c flatpak-remote-add -s h -l help --description 'Show help options and exit.'
complete -c flatpak-remote-add -l from --description 'Assume the URI is a . flatpakrepo file rather than the repository itself.'
complete -c flatpak-remote-add -l user --description 'Modify the per-user configuration.'
complete -c flatpak-remote-add -l system --description 'Modify the default system-wide configuration.'
complete -c flatpak-remote-add -l installation --description 'Modify a system-wide installation specified by NAME among those defined in /e…'
complete -c flatpak-remote-add -l no-gpg-verify --description 'Disable GPG verification for the added remote.'
complete -c flatpak-remote-add -l prio --description 'Set the priority for the remote.  Default is 1, higher is more prioritized.'
complete -c flatpak-remote-add -l no-enumerate --description 'Mark the remote as not enumerated.'
complete -c flatpak-remote-add -l no-use-for-deps --description 'Mark the remote as not to be used for automatic runtime dependency resolution.'
complete -c flatpak-remote-add -l if-not-exists --description 'Do nothing if the provided remote already exists.'
complete -c flatpak-remote-add -l disable --description 'Disable the added remote.'
complete -c flatpak-remote-add -l title --description 'A title for the remote, e. g.  for display in a UI.'
complete -c flatpak-remote-add -l default-branch --description 'A default branch for the remote, mainly for use in a UI.'
complete -c flatpak-remote-add -l gpg-import --description 'Import gpg keys from the specified keyring file as trusted for the new remote.'
complete -c flatpak-remote-add -s v -l verbose --description 'Print debug information during command processing.'
complete -c flatpak-remote-add -l ostree-verbose --description 'Print OSTree debug information during command processing.'

