# flatpak-document-info
# Autogenerated from man page manpages/flatpak-document-info.1
complete -c flatpak-document-info -s h -l help --description 'Show help options and exit.'
complete -c flatpak-document-info -s v -l verbose --description 'Print debug information during command processing.'
complete -c flatpak-document-info -l ostree-verbose --description 'Print OSTree debug information during command processing.'

