# gdk-pixbuf-query-loaders
# Autogenerated from man page manpages/gdk-pixbuf-query-loaders.1
complete -c gdk-pixbuf-query-loaders -l update-cache --description 'Write the output to the default cache location instead of stdout.'

