# genl-ctrl-list
# Autogenerated from man page manpages/genl-ctrl-list.8
complete -c genl-ctrl-list -s h -l help --description 'Print help text to console and exit.'
complete -c genl-ctrl-list -s v -l version --description 'Print versioning information to console and exit.'
complete -c genl-ctrl-list -s d -l details --description 'Include additional detailed information for each Generic Netlink family that …'

