# getcifsacl
# Autogenerated from man page manpages/getcifsacl.1
complete -c getcifsacl -s v --description 'Print version number and exit.'
complete -c getcifsacl -s r --description 'Display a security descriptor in raw mode.'

