# gethostip
# Autogenerated from man page manpages/gethostip.1
complete -c gethostip -s d --description 'Output the IP address in decimal format.'
complete -c gethostip -s x --description 'Output the IP address in hexadecimal format.'
complete -c gethostip -s n --description 'Output the host\'s canonical name.'

