# gifbuild
# Autogenerated from man page manpages/gifbuild.1
complete -c gifbuild -s v --description '.'
complete -c gifbuild -s d --description '.'
complete -c gifbuild -s t --description '.'
complete -c gifbuild -s h --description '.'

