# gifcolor
# Autogenerated from man page manpages/gifcolor.1
complete -c gifcolor -s v --description 'Verbose mode (show progress).  Enables printout of running scan lines.'
complete -c gifcolor -s b --description 'Set the image\\*(Aqs backround color to a given numeric index.'
complete -c gifcolor -s h --description 'Print one line of command line help, similar to Usage above.'

