# giffix
# Autogenerated from man page manpages/giffix.1
complete -c giffix -s t --description 'Verbose mode (show progress).  Enables printout of running scan lines.'
complete -c giffix -s h --description 'Print one line of command line help, similar to Usage above.'

