# git-credential-cache
# Autogenerated from man page manpages/git-credential-cache.1
complete -c git-credential-cache -l timeout --description 'Number of seconds to cache credentials (default: 900).'
complete -c git-credential-cache -l socket --description 'Use <path> to contact a running cache daemon (or start a new cache daemon if …'

