# git-check-mailmap
# Autogenerated from man page manpages/git-check-mailmap.1
complete -c git-check-mailmap -l stdin --description 'Read contacts, one per line, from the standard input after exhausting contact…'

