# git-write-tree
# Autogenerated from man page manpages/git-write-tree.1
complete -c git-write-tree -l missing-ok --description 'Normally git write-tree ensures that the objects referenced by the directory …'
complete -c git-write-tree -l prefix --description 'Writes a tree object that represents a subdirectory <prefix>.'

