# git-multi-pack-index
# Autogenerated from man page manpages/git-multi-pack-index.1
complete -c git-multi-pack-index -l object-dir --description 'Use given directory for the location of Git objects.'

