# grap2graph
# Autogenerated from man page manpages/grap2graph.1
complete -c grap2graph -o unsafe --description 'Run  pic (1) and  groff (1) in the `unsafe\' mode enabling the PIC macro  sh t…'
complete -c grap2graph -o format --description 'Specify an output format; the default is PNG (Portable Network Graphics).'

