# grub-editenv
# Autogenerated from man page manpages/grub-editenv.1
complete -c grub-editenv -s '?' -l help --description 'give this help list.'
complete -c grub-editenv -l usage --description 'give a short usage message.'
complete -c grub-editenv -s v -l verbose --description 'print verbose messages.'
complete -c grub-editenv -s V -l version --description 'print program version Options:.'

