# grub-kbdcomp
# Autogenerated from man page manpages/grub-kbdcomp.1
complete -c grub-kbdcomp -s h -l help --description 'print this message and exit.'
complete -c grub-kbdcomp -s V -l version --description 'print the version information and exit.'
complete -c grub-kbdcomp -s o -l output --description 'save output in FILE [required].'

