# gst-device-monitor-1
# Autogenerated from man page manpages/gst-device-monitor-1.0.1
complete -c gst-device-monitor-1 -l help --description 'Print help synopsis and available command line options.'
complete -c gst-device-monitor-1 -l version --description 'Print version and exit.'

