# gst-stats-1
# Autogenerated from man page manpages/gst-stats-1.0.1
complete -c gst-stats-1 -s h -l help --description 'Print help synopsis and available FLAGS.'
complete -c gst-stats-1 -l gst-help-all --description 'Show all help options .'

