# gtester-report
# Autogenerated from man page manpages/gtester-report.1
complete -c gtester-report -s h -l help --description 'print help and exit.'
complete -c gtester-report -s v -l version --description 'print version information and exit.'
complete -c gtester-report -s s -l subunit --description 'Output subunit.  Needs python-subunit.'

