# gtk-launch
# Autogenerated from man page manpages/gtk-launch.1
complete -c gtk-launch -s '?' -l help --description 'Prints a short help text and exits.'
complete -c gtk-launch -l version --description 'Prints the program version and exits.'

