# gtk-builder-tool
# Autogenerated from man page manpages/gtk-builder-tool.1
complete -c gtk-builder-tool -l replace --description '.'
complete -c gtk-builder-tool -l id --description '.'
complete -c gtk-builder-tool -l css --description '.'

