# hzip
# Autogenerated from man page manpages/hzip.1
complete -c hzip -s h --description 'Display short help description.'
complete -c hzip -s P --description 'Encrypted compression by an arbitrary length password.'

