# i3-config-wizard
# Autogenerated from man page manpages/i3-config-wizard.1
complete -c i3-config-wizard -s s -l socket --description 'Overwrites the path to the i3 IPC socket.'
complete -c i3-config-wizard -s m -l modifier --description 'Generates the configuration file headlessly.  Accepts win or alt.'
complete -c i3-config-wizard -s v -l version --description 'Display version number and exit.'
complete -c i3-config-wizard -s h -l help --description 'Display a short help message and exit.'

