# i3bar
# Autogenerated from man page manpages/i3bar.1
complete -c i3bar -s s -l socket --description 'Overwrites the path to the i3 IPC socket.'
complete -c i3bar -s b -l bar_id --description 'Specifies the bar ID for which to get the configuration from i3.'
complete -c i3bar -s v -l version --description 'Display version number and exit.'
complete -c i3bar -s h -l help --description 'Display a short help-message and exit.'

