# i3status
# Autogenerated from man page manpages/i3status.1
complete -c i3status -s c --description 'Specifies an alternate configuration file path.'
complete -c i3status -o fn -o misc-fixed-medium-r-normal--13-120-75-75-C-70-iso8859-1 --description 'USING I3STATUS WITH XMOBAR.'

