# idevicenotificationproxy
# Autogenerated from man page manpages/idevicenotificationproxy.1
complete -c idevicenotificationproxy -s u -l udid --description 'target specific device by UDID.'
complete -c idevicenotificationproxy -s d -l debug --description 'enable communication debugging.'
complete -c idevicenotificationproxy -s h -l help --description 'prints usage information.'

