# idevicediagnostics
# Autogenerated from man page manpages/idevicediagnostics.1
complete -c idevicediagnostics -s u -l udid --description 'target specific device by UDID.'
complete -c idevicediagnostics -s d -l debug --description 'enable communication debugging.'
complete -c idevicediagnostics -s h -l help --description 'prints usage information.'

