# idevicepair
# Autogenerated from man page manpages/idevicepair.1
complete -c idevicepair -s u -l udid --description 'target specific device by UDID.'
complete -c idevicepair -s d -l debug --description 'enable communication debugging.'
complete -c idevicepair -s h -l help --description 'prints usage information.'

