# idevicedebug
# Autogenerated from man page manpages/idevicedebug.1
complete -c idevicedebug -s e -l env --description 'set environment variable NAME to VALUE.'
complete -c idevicedebug -s u -l udid --description 'target specific device by UDID.'
complete -c idevicedebug -s d -l debug --description 'enable communication debugging.'
complete -c idevicedebug -s h -l help --description 'prints usage information.'

