# idevicename
# Autogenerated from man page manpages/idevicename.1
complete -c idevicename -s d -l debug --description 'enable communication debugging.'
complete -c idevicename -s u -l udid --description 'target specific device by UDID.'
complete -c idevicename -s h -l help --description 'prints usage information.'

