# idevicedebugserverproxy
# Autogenerated from man page manpages/idevicedebugserverproxy.1
complete -c idevicedebugserverproxy -s u -l udid --description 'target specific device by UDID.'
complete -c idevicedebugserverproxy -s d -l debug --description 'enable communication debugging.'
complete -c idevicedebugserverproxy -s h -l help --description 'prints usage information.'

