# idevicescreenshot
# Autogenerated from man page manpages/idevicescreenshot.1
complete -c idevicescreenshot -s d -l debug --description 'enable communication debugging.'
complete -c idevicescreenshot -s u -l udid --description 'target specific device by UDID.'
complete -c idevicescreenshot -s h -l help --description 'prints usage information.'

