# idevicesyslog
# Autogenerated from man page manpages/idevicesyslog.1
complete -c idevicesyslog -s d -l debug --description 'enable communication debugging.'
complete -c idevicesyslog -s u -l udid --description 'target specific device by UDID.'
complete -c idevicesyslog -s h -l help --description 'prints usage information.'

