# idevicebackup
# Autogenerated from man page manpages/idevicebackup.1
complete -c idevicebackup -s u -l udid --description 'target specific device by UDID.'
complete -c idevicebackup -s d -l debug --description 'enable communication debugging.'
complete -c idevicebackup -s h -l help --description 'prints usage information.'

