# ideviceenterrecovery
# Autogenerated from man page manpages/ideviceenterrecovery.1
complete -c ideviceenterrecovery -s d -l debug --description 'enable communication debugging.'
complete -c ideviceenterrecovery -s h -l help --description 'prints usage information.'

