# ideviceprovision
# Autogenerated from man page manpages/ideviceprovision.1
complete -c ideviceprovision -s u -l udid --description 'target specific device by UDID.'
complete -c ideviceprovision -s x -l xml --description 'print XML output when using the \'dump\' command.'
complete -c ideviceprovision -s d -l debug --description 'enable communication debugging.'
complete -c ideviceprovision -s h -l help --description 'prints usage information.'

