# ifnames
# Autogenerated from man page manpages/ifnames.1
complete -c ifnames -s h -l help --description 'print this help, then exit.'
complete -c ifnames -s V -l version --description 'print version number, then exit AUTHOR Written by David J.'

