# isaset
# Autogenerated from man page manpages/isaset.8
complete -c isaset -s f --description 'Enable flat address space mode.'
complete -c isaset -s y --description 'Disable interactive mode.'
complete -c isaset -s W --description 'Perform a 16-bit write.'
complete -c isaset -s L --description 'Perform a 32-bit write.'

