# isosize
# Autogenerated from man page manpages/isosize.8
complete -c isosize -s x -l sectors --description 'Show the block count and block size in human-readable form.'
complete -c isosize -s d -l divisor --description 'Only has an effect when.'

