# iwlist
# Autogenerated from man page manpages/iwlist.8
complete -c iwlist -l version --description 'Display the version of the tools, as well as the recommended and current Wire…'
complete -c iwlist -l help --description 'Display short help message.'

