# jack_load
# Autogenerated from man page manpages/jack_load.1
complete -c jack_load -s i -l init --description 'br initialization string passed to the in-process client.'
complete -c jack_load -s s -l server --description 'br Name of JACK server to connect to.'
complete -c jack_load -s w -l wait --description 'Wait for a signal (eg.  from Ctrl-c) and then unload the client.'

