# json-glib-format
# Autogenerated from man page manpages/json-glib-format.1
complete -c json-glib-format -s h -l help --description '.'
complete -c json-glib-format -s p -l prettify --description '.'
complete -c json-glib-format -l indent-spaces --description '.'

