# kbd_mode
# Autogenerated from man page manpages/kbd_mode.1
complete -c kbd_mode -s s --description '.'
complete -c kbd_mode -s k --description '.'
complete -c kbd_mode -s a --description '.'
complete -c kbd_mode -s u --description '.'

