# kernel-install
# Autogenerated from man page manpages/kernel-install.8
complete -c kernel-install -s v -l verbose --description 'Output additional information about operations being performed.'
complete -c kernel-install -s h -l help --description 'Print a short help text and exit.'

