# kmod
# Autogenerated from man page manpages/kmod.8
complete -c kmod -s V -l version --description 'Show the program version and exit.'
complete -c kmod -s h -l help --description 'Show the help message.'

