# kproplog
# Autogenerated from man page manpages/kproplog.8
complete -c kproplog -s R --description 'Reset the update log.   This forces full resynchronization.'
complete -c kproplog -s h --description 'Display a summary of the update log.'
complete -c kproplog -s e --description 'Display the last num update entries in the log.'
complete -c kproplog -s v --description 'Display individual attributes per update.'

