# kswitch
# Autogenerated from man page manpages/kswitch.1
complete -c kswitch -s c --description 'Directly specifies the credential cache to be made primary.'
complete -c kswitch -s p --description 'Causes the cache collection to be searched for a cache containing credentials…'

