# laptop-detect
# Autogenerated from man page manpages/laptop-detect.8
complete -c laptop-detect -s h -l help --description 'Output help information and exit.'
complete -c laptop-detect -s v -l verbose --description 'be verbose (messages go to STDOUT).'

