# ldbadd
# Autogenerated from man page manpages/ldbadd.1
complete -c ldbadd -s h --description 'Show list of available options.'
complete -c ldbadd -s H --description 'LDB URL to connect to.  See ldb(3) for details.'

