# ldbdel
# Autogenerated from man page manpages/ldbdel.1
complete -c ldbdel -s h --description 'Show list of available options.'
complete -c ldbdel -s H --description 'LDB URL to connect to.  See ldb(3) for details.'

