# ldns-nsec3-hash
# Autogenerated from man page manpages/ldns-nsec3-hash.1
complete -c ldns-nsec3-hash -s a --description 'Use the given algorithm number for the hash calculation.'
complete -c ldns-nsec3-hash -s s --description 'Use the given salt for the hash calculation.'
complete -c ldns-nsec3-hash -s t --description 'Use count iterations for the hash calculation.'

