# ldns-zcat
# Autogenerated from man page manpages/ldns-zcat.1
complete -c ldns-zcat -s o --description 'use ORIGIN when reading in the zone.'
complete -c ldns-zcat -s v --description 'show the version number and exit.'

