# ldns-test-edns
# Autogenerated from man page manpages/ldns-test-edns.1
complete -c ldns-test-edns -s i --description 'after another, with no other explanations, and if none work or no IP addresse…'

