# libinput-measure-touchpad-pressure
# Autogenerated from man page manpages/libinput-measure-touchpad-pressure.1
complete -c libinput-measure-touchpad-pressure -l help --description 'Print help.'
complete -c libinput-measure-touchpad-pressure -l touch-thresholds --description 'Set the logical touch pressure thresholds to  down and  up, respectively.'
complete -c libinput-measure-touchpad-pressure -l palm-threshold --description 'Assume a palm threshold of N.'

