# libinput-quirks
# Autogenerated from man page manpages/libinput-quirks.1
complete -c libinput-quirks -l data-dir --description 'Use the given directory as data directory for quirks files.'
complete -c libinput-quirks -l help --description 'Print help.'
complete -c libinput-quirks -l verbose --description 'Use verbose output, useful for debugging.'

