# libinput
# Autogenerated from man page manpages/libinput.1
complete -c libinput -l help --description 'Print help and exit.'
complete -c libinput -l version --description 'Print the version and exit COMMANDS.'

