# libwacom-list-local-devices
# Autogenerated from man page manpages/libwacom-list-local-devices.1
complete -c libwacom-list-local-devices -l database --description 'Sets the data directory path to be used.'

