# link
# Autogenerated from man page manpages/link.1
complete -c link -l help --description 'display this help and exit.'
complete -c link -l version --description 'output version information and exit AUTHOR Written by Michael Stone.'

