# loadunimap
# Autogenerated from man page manpages/loadunimap.8
complete -c loadunimap -s o --description 'oldmap option is given, the old map is saved in the file specified.'
complete -c loadunimap -s C --description 'option.'

