# logname
# Autogenerated from man page manpages/logname.1
complete -c logname -l help --description 'display this help and exit.'
complete -c logname -l version --description 'output version information and exit AUTHOR Written by FIXME: unknown.'

