# mdmon
# Autogenerated from man page manpages/mdmon.8
complete -c mdmon -l foreground --description 'Normally,  mdmon will fork and continue in the background.'
complete -c mdmon -l takeover --description 'This instructs  mdmon to replace any active  mdmon which is currently monitor…'
complete -c mdmon -l all --description 'This tells mdmon to find any active containers and start monitoring each of t…'
complete -c mdmon -l all-active-arrays --description 'Note that mdmon is automatically started by mdadm when needed and so does not…'

