# mkcp
# Autogenerated from man page manpages/mkcp.8
complete -c mkcp -s s -l snapshot --description 'Create a snapshot.'
complete -c mkcp -s p -l print --description 'Print the checkpoint number when successfully created.'
complete -c mkcp -s h -l help --description 'Display help message and exit.'
complete -c mkcp -s V -l version --description 'Display version and exit.'

