# mtrace
# Autogenerated from man page manpages/mtrace.1
complete -c mtrace -l help --description 'Print help and exit.'
complete -c mtrace -l version --description 'Print version information and exit.'

