# nbd-server
# Autogenerated from man page manpages/nbd-server.1
complete -c nbd-server -s r --description 'Export the file read-only.'
complete -c nbd-server -s m --description 'Work with multiple files.'
complete -c nbd-server -s c --description 'Copy on write.'
complete -c nbd-server -s C --description 'Specify configuration file.'
complete -c nbd-server -s M --description 'Specify the maximum number of opened connections.'
complete -c nbd-server -s V --description 'Output the version of nbd-server, and exit.'
complete -c nbd-server -s d --description 'Do not fork.  Useful for debugging.'

