# ndctl-sanitize-dimm
# Autogenerated from man page manpages/ndctl-sanitize-dimm.1
complete -c ndctl-sanitize-dimm -s b -l bus --description '.'
complete -c ndctl-sanitize-dimm -s c -l crypto-erase --description '.'
complete -c ndctl-sanitize-dimm -s o -l ovewrite --description '.'
complete -c ndctl-sanitize-dimm -s m -l master_passphrase --description '.'
complete -c ndctl-sanitize-dimm -l verbose --description '.'

