# ndctl-write-labels
# Autogenerated from man page manpages/ndctl-write-labels.1
complete -c ndctl-write-labels -l bus --description '.'
complete -c ndctl-write-labels -s b --description '.'
complete -c ndctl-write-labels -s v --description '.'
complete -c ndctl-write-labels -s i -l input --description '.'

