# ndctl-disable-namespace
# Autogenerated from man page manpages/ndctl-disable-namespace.1
complete -c ndctl-disable-namespace -s r -l region --description 'A \'regionX\' device name, or a region id number.'
complete -c ndctl-disable-namespace -s b -l bus --description '.'
complete -c ndctl-disable-namespace -s v -l verbose --description '.'

