# ndctl-freeze-security
# Autogenerated from man page manpages/ndctl-freeze-security.1
complete -c ndctl-freeze-security -s b -l bus --description '.'
complete -c ndctl-freeze-security -s v -l verbose --description '.'

