# ndctl-check-labels
# Autogenerated from man page manpages/ndctl-check-labels.1
complete -c ndctl-check-labels -l bus --description '.'
complete -c ndctl-check-labels -s b --description '.'
complete -c ndctl-check-labels -s v --description '.'

