# ndctl-update-passphrase
# Autogenerated from man page manpages/ndctl-update-passphrase.1
complete -c ndctl-update-passphrase -s b -l bus --description '.'
complete -c ndctl-update-passphrase -s k -l key_handle --description '.'
complete -c ndctl-update-passphrase -s m -l master-passphrase --description '.'
complete -c ndctl-update-passphrase -s v -l verbose --description '.'

