# ndctl-enable-namespace
# Autogenerated from man page manpages/ndctl-enable-namespace.1
complete -c ndctl-enable-namespace -s r -l region --description 'A \'regionX\' device name, or a region id number.'
complete -c ndctl-enable-namespace -s b -l bus --description '.'
complete -c ndctl-enable-namespace -s v -l verbose --description '.'

