# ndctl-check-namespace
# Autogenerated from man page manpages/ndctl-check-namespace.1
complete -c ndctl-check-namespace -s R -l repair --description '.'
complete -c ndctl-check-namespace -s L -l rewrite-log --description '.'
complete -c ndctl-check-namespace -s f -l force --description '.'
complete -c ndctl-check-namespace -s v -l verbose --description '.'
complete -c ndctl-check-namespace -s r -l region --description 'A \'regionX\' device name, or a region id number.'
complete -c ndctl-check-namespace -s b -l bus --description '.'

