# ndctl-init-labels
# Autogenerated from man page manpages/ndctl-init-labels.1
complete -c ndctl-init-labels -l bus --description '.'
complete -c ndctl-init-labels -s b --description '.'
complete -c ndctl-init-labels -s v --description '.'
complete -c ndctl-init-labels -s f -l force --description '.'
complete -c ndctl-init-labels -s V -l label-version --description '.'

