# ndctl-remove-passphrase
# Autogenerated from man page manpages/ndctl-remove-passphrase.1
complete -c ndctl-remove-passphrase -s b -l bus --description '.'
complete -c ndctl-remove-passphrase -s v -l verbose --description '.'

