# ndctl-zero-labels
# Autogenerated from man page manpages/ndctl-zero-labels.1
complete -c ndctl-zero-labels -l bus --description '.'
complete -c ndctl-zero-labels -s b --description '.'
complete -c ndctl-zero-labels -s v --description '.'

