# ndctl-destroy-namespace
# Autogenerated from man page manpages/ndctl-destroy-namespace.1
complete -c ndctl-destroy-namespace -s r -l region --description 'A \'regionX\' device name, or a region id number.'
complete -c ndctl-destroy-namespace -s b -l bus --description '.'
complete -c ndctl-destroy-namespace -s v -l verbose --description '.'
complete -c ndctl-destroy-namespace -s f -l force --description '.'

