# ndctl-wait-overwrite
# Autogenerated from man page manpages/ndctl-wait-overwrite.1
complete -c ndctl-wait-overwrite -s b -l bus --description '.'
complete -c ndctl-wait-overwrite -s v -l verbose --description '.'

