# ndctl-load-keys
# Autogenerated from man page manpages/ndctl-load-keys.1
complete -c ndctl-load-keys -s p -l key-path --description '.'
complete -c ndctl-load-keys -s t -l tpm-handle --description '.'

