# ndctl-read-labels
# Autogenerated from man page manpages/ndctl-read-labels.1
complete -c ndctl-read-labels -l bus --description '.'
complete -c ndctl-read-labels -s b --description '.'
complete -c ndctl-read-labels -s v --description '.'
complete -c ndctl-read-labels -s o -l output --description '.'
complete -c ndctl-read-labels -s j -l json --description '.'

