# ndctl-update-firmware
# Autogenerated from man page manpages/ndctl-update-firmware.1
complete -c ndctl-update-firmware -s b -l bus --description '.'
complete -c ndctl-update-firmware -s f -l firmware --description '.'
complete -c ndctl-update-firmware -s v -l verbose --description '.'

