# ndctl-setup-passphrase
# Autogenerated from man page manpages/ndctl-setup-passphrase.1
complete -c ndctl-setup-passphrase -s b -l bus --description '.'
complete -c ndctl-setup-passphrase -s k -l key_handle --description '.'
complete -c ndctl-setup-passphrase -s m -l master-passphrase --description '.'
complete -c ndctl-setup-passphrase -s v -l verbose --description '.'

