# ndptool
# Autogenerated from man page manpages/ndptool.8
complete -c ndptool -s h -l help --description 'Print help text to console and exit.'
complete -c ndptool -s v -l verbose --description 'Increase output verbosity.'
complete -c ndptool -s t -l msg-type --description 'Specified message type.'
complete -c ndptool -s i -l ifname --description 'Specified interface name.'
complete -c ndptool -s U -l unsolicited --description 'Send Unsolicited NA.'

