# newusers
# Autogenerated from man page manpages/newusers.8
complete -c newusers -s h -l help --description 'Display help message and exit.'
complete -c newusers -s r -l system --description 'Create a system account.'
complete -c newusers -s R -l rootCHROOT_DIR --description 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c newusers -l root --description '.'

