# nfsdcltrack
# Autogenerated from man page manpages/nfsdcltrack.8
complete -c nfsdcltrack -s d -l debug --description 'Enable debug level logging.'
complete -c nfsdcltrack -s f -l foreground --description 'Log to stderr instead of syslog.'

