# nilfs-resize
# Autogenerated from man page manpages/nilfs-resize.8
complete -c nilfs-resize -s y -l yes -l assume-yes --description 'Assume Yes to all queries and do not prompt.'
complete -c nilfs-resize -s h -l help --description 'Display help message and exit.'
complete -c nilfs-resize -s v -l verbose --description 'Verbose mode.'
complete -c nilfs-resize -s V -l version --description 'Display version and exit.  AUTHOR Ryusuke Konishi <konishi. ryusuke@lab. ntt.'

