# nm-initrd-generator
# Autogenerated from man page manpages/nm-initrd-generator.8
complete -c nm-initrd-generator -s c -l connections-dir --description 'Output connection directory.'
complete -c nm-initrd-generator -s d -l sysfs-dir --description 'The sysfs mount point.'
complete -c nm-initrd-generator -s s -l stdout --description 'Dump connections to standard output.  Useful for debugging.'

