# nohup
# Autogenerated from man page manpages/nohup.1
complete -c nohup -l help --description 'display this help and exit.'
complete -c nohup -l version --description 'output version information and exit.'

