# nologin
# Autogenerated from man page manpages/nologin.8
complete -c nologin -s h -l help --description 'Display help text and exit.'
complete -c nologin -s V -l version --description 'Display version information and exit.'

