# nss-mymachines
# Autogenerated from man page manpages/nss-mymachines.8
complete -c nss-mymachines -l private-network --description 'in systemd-nspawn(1)).'
complete -c nss-mymachines -l private-users --description 'in systemd-nspawn(1)).'

