# ntfscmp
# Autogenerated from man page manpages/ntfscmp.8
complete -c ntfscmp -s P -l no-progress-bar --description 'Don\'t show progress bars.'
complete -c ntfscmp -s v -l verbose --description 'More informational output.'
complete -c ntfscmp -s h -l help --description 'Display help and exit.'

