# ntfs-3g
# Autogenerated from man page manpages/ntfs-3g.probe.8
complete -c ntfs-3g -s r -l readonly --description 'Test if the volume can be mounted read-only.'
complete -c ntfs-3g -s w -l readwrite --description 'Test if the volume can be mounted read-write.'
complete -c ntfs-3g -s h -l help --description 'Display help and exit.'

