# omxregister-bellagio
# Autogenerated from man page manpages/omxregister-bellagio.1
complete -c omxregister-bellagio -s v --description 'Display a verbose output, listing all the components registered.'
complete -c omxregister-bellagio -s h --description 'Display help.'

