# opj_dump
# Autogenerated from man page manpages/opj_dump.1
complete -c opj_dump -s i --description '(jpeg2000 input file name).'
complete -c opj_dump -o ImgDir --description '(directory containing jpeg2000 input files) AUTHORS Copyright (c) 2010, Mathi…'

