# ostree-init
# Autogenerated from man page manpages/ostree-init.1
complete -c ostree-init -l mode --description 'Initialize repository in given mode (bare, bare-user, bare-user-only, archive…'
complete -c ostree-init -l collection-id --description 'Set the collection ID of the repository.'

