# ostree-find-remotes
# Autogenerated from man page manpages/ostree-find-remotes.1
complete -c ostree-find-remotes -l disable-fsync --description 'Do not invoke fsync().'
complete -c ostree-find-remotes -l finders --description 'Use the specified comma separated list of finders rather than the default set.'
complete -c ostree-find-remotes -l pull --description 'Pull the most recent commit found for each ref.'

