# ostree-create-usb
# Autogenerated from man page manpages/ostree-create-usb.1
complete -c ostree-create-usb -l disable-fsync --description 'Do not invoke fsync().'
complete -c ostree-create-usb -l destination-repo --description 'Create the repository in DEST under MOUNT-PATH, rather than the default locat…'
complete -c ostree-create-usb -l commit --description 'Pull COMMIT instead of whatever REF points to.'

