# ostree-gpg-sign
# Autogenerated from man page manpages/ostree-gpg-sign.1
complete -c ostree-gpg-sign -l delete --description 'Delete signatures having any of the GPG KEY-IDs.'
complete -c ostree-gpg-sign -l gpg-homedir --description 'GPG Homedir to use when looking for keyrings.'

