# ostree-admin-set-origin
# Autogenerated from man page manpages/ostree-admin-set-origin.1
complete -c ostree-admin-set-origin -l set --description 'Set an option for the remote.'
complete -c ostree-admin-set-origin -l index --description 'Change the origin of the deployment numbered INDEX (starting from 0).'

