# ostree-static-delta
# Autogenerated from man page manpages/ostree-static-delta.1
complete -c ostree-static-delta -l from --description '.'
complete -c ostree-static-delta -l to --description '.'
complete -c ostree-static-delta -l empty --description '.'
complete -c ostree-static-delta -l max-usize --description '.'

