# ostree-admin-config-diff
# Autogenerated from man page manpages/ostree-admin-config-diff.1
complete -c ostree-admin-config-diff -l os --description 'Use a different operating system stateroot than the current one.'

