# ostree-pull-local
# Autogenerated from man page manpages/ostree-pull-local.1
complete -c ostree-pull-local -l remote --description 'Add REMOTE to refspec.'
complete -c ostree-pull-local -l disable-fsync --description 'Do no invoke fsync().'
complete -c ostree-pull-local -l untrusted --description 'Do not trust source, verify checksums and don\\*(Aqt hardlink into source.'

