# ostree-admin
# Autogenerated from man page manpages/ostree-admin.1
complete -c ostree-admin -l help -s h --description 'Usage help.'
complete -c ostree-admin -l sysroot --description 'Creates a new OSTree sysroot at PATH.'
complete -c ostree-admin -l print-current-dir --description 'Prints the full path to the deployment directory for the currently active dep…'

