# ostree
# Autogenerated from man page manpages/ostree.1
complete -c ostree -l repo --description 'For most commands, a repository is required.'
complete -c ostree -s v -l verbose --description 'Produce debug level output.'
complete -c ostree -l set --description 'in ostree remote add.'

