# ostree-admin-unlock
# Autogenerated from man page manpages/ostree-admin-unlock.1
complete -c ostree-admin-unlock -l hotfix --description 'If this option is provided, the current deployment will be cloned as a rollba…'

