# ownership
# Autogenerated from man page manpages/ownership.8
complete -c ownership -s d -l dev-mem --description 'Read memory from device FILE (default: /dev/mem).'
complete -c ownership -s h -l help --description 'Display usage information and exit.'
complete -c ownership -s V -l version --description 'Display the version and exit.'

