# pipewire
# Autogenerated from man page manpages/pipewire.1
complete -c pipewire -s h -l help --description 'Show help.'
complete -c pipewire -s v -l version --description 'Show version information.'
complete -c pipewire -s n -l name --description 'Set the daemon name (Default pipewire-1).'

