# pipewire-monitor
# Autogenerated from man page manpages/pipewire-monitor.1
complete -c pipewire-monitor -s h -l help --description 'Show help.'
complete -c pipewire-monitor -l version --description 'Show version information.  AUTHORS The PipeWire Developers <https://github.'

