# pldd
# Autogenerated from man page manpages/pldd.1
complete -c pldd -s '?' -l help --description 'Display program help message.'
complete -c pldd -l usage --description 'Display a short usage message.'
complete -c pldd -s V -l version --description 'Display the program version.'

