# prezip-bin
# Autogenerated from man page manpages/prezip-bin.1
complete -c prezip-bin -s V --description 'Display prezip-bin version number to standard output.'
complete -c prezip-bin -s d --description 'Read a compressed word list from standard input and decompress it to standard…'
complete -c prezip-bin -s z --description 'Read a binary word list from standard input and compress it to standard outpu…'

