# printf
# Autogenerated from man page manpages/printf.1
complete -c printf -l help --description 'display this help and exit.'
complete -c printf -l version --description 'output version information and exit .'

