# printenv
# Autogenerated from man page manpages/printenv.1
complete -c printenv -s 0 -l null --description 'end each output line with NUL, not newline.'
complete -c printenv -l help --description 'display this help and exit.'
complete -c printenv -l version --description 'output version information and exit.'

