# prtstat
# Autogenerated from man page manpages/prtstat.1
complete -c prtstat -s r -l raw --description 'Print the information in raw format.'
complete -c prtstat -s V -l version --description 'Show the version information for prtstat .  FILES.'

