# pvremove
# Autogenerated from man page manpages/pvremove.8
complete -c pvremove -l commandprofile --description '.'
complete -c pvremove -l config --description '.'
complete -c pvremove -s d -l debug --description '.'
complete -c pvremove -l driverloaded --description '.'
complete -c pvremove -s f -l force --description '.'
complete -c pvremove -s h -l help --description '.'
complete -c pvremove -l lockopt --description '.'
complete -c pvremove -l longhelp --description '.'
complete -c pvremove -l profile --description '.'
complete -c pvremove -s q -l quiet --description '.'
complete -c pvremove -l reportformat --description '.'
complete -c pvremove -s t -l test --description '.'
complete -c pvremove -s v -l verbose --description '.'
complete -c pvremove -l version --description '.'
complete -c pvremove -s y -l yes --description '.'

