# pwdx
# Autogenerated from man page manpages/pwdx.1
complete -c pwdx -s V -l version --description 'Output version information and exit.'
complete -c pwdx -s h -l help --description 'Output help screen and exit.'

