# rdma-link
# Autogenerated from man page manpages/rdma-link.8
complete -c rdma-link -s V --description '.'
complete -c rdma-link -s d --description 'rdma link show [  DEV/PORT_INDEX  ] rdma link help.'

