# rdma-resource
# Autogenerated from man page manpages/rdma-resource.8
complete -c rdma-resource -s j --description '.'
complete -c rdma-resource -s d --description 'rdma resource show [  DEV/PORT_INDEX  ] rdma resource help.'

