# rdma-dev
# Autogenerated from man page manpages/rdma-dev.8
complete -c rdma-dev -s V --description '.'
complete -c rdma-dev -s d --description 'rdma dev show [  DEV  ] rdma dev set [  DEV  ] name NEWNAME rdma dev help.'

