# recode-sr-latin
# Autogenerated from man page manpages/recode-sr-latin.1
complete -c recode-sr-latin -s h -l help --description 'display this help and exit.'
complete -c recode-sr-latin -s V -l version --description 'output version information and exit AUTHOR Written by Danilo Segan and Bruno …'

