# resize
# Autogenerated from man page manpages/resize.f2fs.8
complete -c resize -s t --description 'Specify the size in sectors.'
complete -c resize -s d --description 'Specify the level of debugging options.'

