# rev
# Autogenerated from man page manpages/rev.1
complete -c rev -s V -l version --description 'Display version information and exit.'
complete -c rev -s h -l help --description 'Display help text and exit.'

