# rmcp
# Autogenerated from man page manpages/rmcp.8
complete -c rmcp -s f -l force --description 'Ignore snapshots or nonexistent checkpoints.'
complete -c rmcp -s i -l interactive --description 'Prompt before any removal.'
complete -c rmcp -s h -l help --description 'Display help message and exit.'
complete -c rmcp -s V -l version --description 'Display version and exit.  AUTHOR Koji Sato, Ryusuke Konishi <konishi.'

