# secret-tool
# Autogenerated from man page manpages/secret-tool.1
complete -c secret-tool -l label --description 'argument.  This label will be displayed in the password manager.'
complete -c secret-tool -l all --description '.'
complete -c secret-tool -l unlock --description '.'

