# setcifsacl
# Autogenerated from man page manpages/setcifsacl.1
complete -c setcifsacl -s h --description 'Print usage message and exit.'
complete -c setcifsacl -s v --description 'Print version number and exit.'
complete -c setcifsacl -s a --description 'Add one or more ACEs to an ACL of a security descriptor.'
complete -c setcifsacl -s D --description 'Delete one or more ACEs from an ACL of a security descriptor.'
complete -c setcifsacl -s M --description 'Modify one or more ACEs from an ACL of a security descriptor.'
complete -c setcifsacl -s S --description 'Set an ACL of security descriptor with the list of ACEs Existing ACL is repla…'

