# setvtrgb
# Autogenerated from man page manpages/setvtrgb.8
complete -c setvtrgb -s h --description 'Prints usage message and exits.'
complete -c setvtrgb -s V --description 'Prints version number and exists.'

