# sload
# Autogenerated from man page manpages/sload.f2fs.8
complete -c sload -s f --description 'Specify the source directory path to be loaded.'
complete -c sload -s t --description 'Specify the mount point path in the partition to load.'
complete -c sload -s d --description 'Specify the level of debugging options.'

