# synclient
# Autogenerated from man page manpages/synclient.1
complete -c synclient -s l --description 'List current user settings.  This is the default if no option is given.'
complete -c synclient -s V --description 'Print version number and exit.'
complete -c synclient -s '?' --description 'Show the help message.'

