# systemd-path
# Autogenerated from man page manpages/systemd-path.1
complete -c systemd-path -l suffix --description 'Printed paths are suffixed by the specified string.'
complete -c systemd-path -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-path -l version --description 'Print a short version string and exit.'

