# systemd-socket-proxyd
# Autogenerated from man page manpages/systemd-socket-proxyd.8
complete -c systemd-socket-proxyd -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-socket-proxyd -l version --description 'Print a short version string and exit.'
complete -c systemd-socket-proxyd -l connections-max -s c --description 'Sets the maximum number of simultaneous connections, defaults to 256.'

