# systemd-ask-password-console
# Autogenerated from man page manpages/systemd-ask-password-console.service.8
complete -c systemd-ask-password-console -l watch -l console --description 'or.'
complete -c systemd-ask-password-console -l wall --description 'command line parameters.  SEE ALSO.'

