# systemd-suspend
# Autogenerated from man page manpages/systemd-suspend.service.8
complete -c systemd-suspend -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-suspend -l version --description 'Print a short version string and exit.'

