# talk
# Autogenerated from man page manpages/talk.1
complete -c talk -s '?' -l help --description 'give this help list.'
complete -c talk -l usage --description 'give a short usage message.'
complete -c talk -s V -l version --description 'print program version AUTHOR Written by Kipp Hickman, Clem Cole, and Peter Mo…'

