# tdbdump
# Autogenerated from man page manpages/tdbdump.8
complete -c tdbdump -s h --description 'Get help information.'
complete -c tdbdump -s k --description 'The -k option restricts dumping to a single key, if found.'
complete -c tdbdump -s e --description 'The -e tries to dump out from a corrupt database.'

