# telinit
# Autogenerated from man page manpages/telinit.8
complete -c telinit -l help --description 'Print a short help text and exit.'
complete -c telinit -l no-wall --description 'Do not send wall message before reboot/halt/power-off.'

