# texindex
# Autogenerated from man page manpages/texindex.1
complete -c texindex -s h -l help --description 'display this help and exit.'
complete -c texindex -l version --description 'display version information and exit.'

