# thin_rmap
# Autogenerated from man page manpages/thin_rmap.8
complete -c thin_rmap -s h -l help --description 'Print help and exit.'
complete -c thin_rmap -s V -l version --description 'Print version information and exit.'
complete -c thin_rmap -l region --description 'Specify range of blocks on the data device.'

