# Thunar
# Autogenerated from man page manpages/Thunar.1
complete -c Thunar -l bulk-rename --description 'option is specified no file managers windows will be opened, but instead the …'
complete -c Thunar -s '?' -l help --description '.'
complete -c Thunar -s v -l version --description '.'
complete -c Thunar -s B --description '.'
complete -c Thunar -l daemon --description '.'
complete -c Thunar -l display --description '.'
complete -c Thunar -s q -l quit --description '.'

