# transmission-gtk
# Autogenerated from man page manpages/transmission-gtk.1
complete -c transmission-gtk -s '?' --description 'Show help options.'
complete -c transmission-gtk -s p --description 'Start with all torrents paused.'
complete -c transmission-gtk -s m --description 'Start minimized in notification area.'
complete -c transmission-gtk -s g --description 'Where to look for configuration files.'

