# true
# Autogenerated from man page manpages/true.1
complete -c true -l help --description 'display this help and exit.'
complete -c true -l version --description 'output version information and exit.'

