# ts_verify
# Autogenerated from man page manpages/ts_verify.1
complete -c ts_verify -s i -l idev --description 'Explicitly choose the original input event device for tslib to use.'
complete -c ts_verify -s h -l help --description '.'

