# tsort
# Autogenerated from man page manpages/tsort.1
complete -c tsort -l help --description 'display this help and exit.'
complete -c tsort -l version --description 'output version information and exit AUTHOR Written by Mark Kettenis.'

