# update-mime-database
# Autogenerated from man page manpages/update-mime-database.1
complete -c update-mime-database -s h --description 'Print out a command summary.'
complete -c update-mime-database -s v --description 'Print out the version information.'
complete -c update-mime-database -s V --description 'Be verbose.'
complete -c update-mime-database -s n --description 'Only update if MIME-DIR/packages/ or a file in that directory is newer than M…'

