# vi
# Autogenerated from man page manpages/vi.1
complete -c vi -o ccommand --description 'Execute  command when editing begins.'
complete -c vi -s l --description 'Start in a special mode useful for the  Lisp programming language.'
complete -c vi -s r -s L --description 'When no argument is supplied with this option, all files to be recovered are …'
complete -c vi -s R --description 'Files are opened read-only when this option is given.'
complete -c vi -s s --description 'Script mode; all feedback for interactive editing is disabled.'
complete -c vi -s t --description 'Read the  tags file, then choose the file and position specified by  tagstrin…'
complete -c vi -s V --description 'Echo command input to standard error, unless it originates from a terminal.'
complete -c vi -s w --description 'Specify the size of the editing window for visual mode.'
complete -c vi -s c --description 'Execute command when editing begins.'

