# whoami
# Autogenerated from man page manpages/whoami.1
complete -c whoami -l help --description 'display this help and exit.'
complete -c whoami -l version --description 'output version information and exit AUTHOR Written by Richard Mlynarik.'

