# word-list-compress
# Autogenerated from man page manpages/word-list-compress.1
complete -c word-list-compress -s c --description 'compress the plain text word list read from standard input.'
complete -c word-list-compress -s d --description 'decompress the compressed word list read from standard input.'

