# x11perfcomp
# Autogenerated from man page manpages/x11perfcomp.1
complete -c x11perfcomp -s r --description 'Specifies that the output should also include relative server performance.'
complete -c x11perfcomp -o ro --description 'Specifies that the output should include only relative server performance.'
complete -c x11perfcomp -s l --description 'Specifies a label file to use.'

