# xclip-copyfile
# Autogenerated from man page manpages/xclip-copyfile.1
complete -c xclip-copyfile -s p --description 'preserve path formation xclip-pastefile pastes the files out of the clipboard…'

