# xdg-screensaver
# Autogenerated from man page manpages/xdg-screensaver.1
complete -c xdg-screensaver -l help --description 'Show command synopsis.'
complete -c xdg-screensaver -l manual --description 'Show this manual page.'
complete -c xdg-screensaver -l version --description 'Show the xdg-utils version information.'

