# xdg-open
# Autogenerated from man page manpages/xdg-open.1
complete -c xdg-open -l help --description 'Show command synopsis.'
complete -c xdg-open -l manual --description 'Show this manual page.'
complete -c xdg-open -l version --description 'Show the xdg-utils version information.'

