# xdriinfo
# Autogenerated from man page manpages/xdriinfo.1
complete -c xdriinfo -o display --description 'Specifies X server to connect to.'
complete -c xdriinfo -o version --description 'Print the program version and exit. PP Valid commands are:.'

