# Xephyr
# Autogenerated from man page manpages/Xephyr.1
complete -c Xephyr -o screen --description 'sets the screen size.'
complete -c Xephyr -o parent --description 'uses existing window  id .'
complete -c Xephyr -o host-cursor --description 'set \'cursor acceleration\': The host\'s cursor is reused.'
complete -c Xephyr -o resizeable --description 'Allow the Xephyr window to be resized, even if not embedded into a parent win…'
complete -c Xephyr -o no-host-grab --description 'Disable grabbing the keyboard and mouse.'

