# xfs_mdrestore
# Autogenerated from man page manpages/xfs_mdrestore.8
complete -c xfs_mdrestore -s g --description 'Shows restore progress on stdout.'
complete -c xfs_mdrestore -s i --description 'Shows metadump information on stdout.'
complete -c xfs_mdrestore -s V --description 'Prints the version number and exits.'

