# xfs_info
# Autogenerated from man page manpages/xfs_info.8
complete -c xfs_info -s t --description 'Specifies an alternate mount table file (default is  /proc/mounts if it exist…'
complete -c xfs_info -s V --description 'Prints the version number and exits.'

