# xlsatoms
# Autogenerated from man page manpages/xlsatoms.1
complete -c xlsatoms -o display --description 'This option specifies the X server to which to connect.'
complete -c xlsatoms -o format --description 'This option specifies a printf-style string used to list each atom <value,nam…'
complete -c xlsatoms -o range --description 'This option specifies the range of atom values to check.'
complete -c xlsatoms -o name --description 'This option specifies the name of an atom to list.'

