# xlsclients
# Autogenerated from man page manpages/xlsclients.1
complete -c xlsclients -o display --description 'This option specifies the X server to contact.'
complete -c xlsclients -s a --description 'This option indicates that clients on all screens should be listed.'
complete -c xlsclients -s l --description 'List in long format, giving the window name, icon name, and class hints in ad…'
complete -c xlsclients -s m --description 'This option specifies the maximum number of characters in a command to print …'
complete -c xlsclients -o version --description 'Print the program version and exit.'

