# xtotroff
# Autogenerated from man page manpages/xtotroff.1
complete -c xtotroff -s r --description 'Set the resolution for all font patterns in R FontMap .'
complete -c xtotroff -s s --description 'Set the point size for all font patterns in R FontMap .'
complete -c xtotroff -s v --description 'Print the version number.'

