# xvinfo
# Autogenerated from man page manpages/xvinfo.1
complete -c xvinfo -o display --description 'This argument allows you to specify the server to query; see X(7).'
complete -c xvinfo -o short --description 'Output less details, to reduce the amount of text.'
complete -c xvinfo -o version --description 'Output program version, then exit.'

