# yes
# Autogenerated from man page manpages/yes.1
complete -c yes -l help --description 'display this help and exit.'
complete -c yes -l version --description 'output version information and exit AUTHOR Written by David MacKenzie.'

